export const meta = {
  name: 'Research and Report',
  description:
    'Research and Report — unbounded best-first web crawl steered by a BRAINER over a persistent id-keyed rabbit-hole store, believing only what a quote-pinned CLAIM LEDGER can prove. A sonnet SCOUT PLANNER decomposes the query into 3-5 search angles (direct + a SKEPTIC angle + a RECENT angle) → parallel haiku SCOUT PROBES sweep each angle → a sonnet SCOUT MERGER folds them into one landscape, naming inter-angle tensions → opus PROSPECTOR names the high-value authoritative source venues → [the brainer looks up OR originates the rabbit-holes worth pursuing, assigning each its venue subset + a steering `note` (what to find + ranked fallbacks) → a sonnet SCHEDULER discovers + sizes the highest-value sources per lane → code bin-packs each lane into 130k-token reader-units and runs ONE sequential haiku reader thread per lane, each yielding quote-pinned CLAIMS a haiku AUDITOR mechanically verifies against the cache and a sonnet LINEAGE CLERK clusters by independent provenance (union-find; corroboration counts clusters, not sources) — claim status and confidence are COMPUTED from ledger topology, never asserted, and may only be lowered; a counter-search that lands nothing is logged as a survived challenge (nullAttack); for build-the-answer queries the brainer authors a stored seeded Python DERIVATION once, a haiku RERUNNER re-executes it whenever an input claim changes, and its variance decomposition steers which leads get read next (a value-of-information stop test) → the brainer returns delta updates (rescore / add / lookupNext / rename / drop), maintains a running resultSoFar keyed to `keyClaimIds`, decides done] until done / rabbithole-dry / wave hard-cap (15) → FINALIZE: an opus INITIATOR names the load-bearing facts + report focus → a sonnet refine pass fact-checks + hardens those facts against the sources, folding every counter-search outcome into the ledger → an opus JUDGE — the sole terminal skeptic, also handed the leftover open rabbit-holes and the power to RETRACT a discredited claim — judges the hardened answer (goal met, verification real, derivation valid) and steers a bounded remediation loop — the brain derives the answer when one is needed, refine re-checks a mis-hardened fact, or the crawl reopens on a real gap → an opus synthesiser writes the 8-section report, its citations linted against the ledger and its confidence floored by the computed value. Pursued-archive (no delete-on-pursue) + pursued memory; scoreHistory rides natively on each rabbit-hole id. Two modes: goal (satisficing) / collect (exhaustive, with a Chao1 coverage estimate gating the plateau stop). Returns per-wave markdown + the claim ledger + refinement + report + _rabbitHoles.json.',
  // ONLY the always-first phase is declared; everything after Scout is driven dynamically by phase() calls in run
  // order — each crawl wave its own phase (Research wN), then Finalize ONLY when a brainer declares done, then Debug
  // only at the very end. Declaring Finalize/Debug statically would pin them ahead of the dynamic wave phases.
  phases: [
    {
      title: 'Scout',
      detail:
        'the seed: a sonnet planner decomposes the query into search angles → parallel haiku probes sweep them (fetching sources with the rabbit-hole footer, each claim quote-pinned) → a sonnet merger folds every probe into one landscape → opus prospector names the high-value authoritative source venues → the brainer (wave 0) ledgers the scout claims, scores the scout rabbit-holes, assigns each its venue subset, and looks up the first wave',
    },
  ],
};
