package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCodexAgentsCommandCompilesAndInstalls exercises the "pfm codex agents"
// CLI adapter end to end inside the path jail: it reads
// {PFM_HOME}/.professor/templates/global/agents/*.md, writes a compiled
// .toml into the pfm-owned generated directory (never beside the source
// .md), and symlinks both shapes into the jailed home's .claude/agents and
// .codex/agents — the same registries pfm install wires.
func TestCodexAgentsCommandCompilesAndInstalls(t *testing.T) {
	jailTest(t)
	home := os.Getenv("PFM_HOME")
	writeCodexCLIFile(
		t,
		filepath.Join(home, ".professor", "templates", "global", "agents", "quirky.md"),
		"---\nname: quirky\ndescription: Uses \"walker fast\" and \"map it now\" verbatim.\ntools: Read\nmodel: sonnet\n---\n\n"+
			"Body has a literal triple quote \"\"\" and a backslash \\ standalone.\n",
	)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"codex", "agents"}, &stdout, &stderr); code != 0 {
		t.Fatalf("codex agents code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "CODEX AGENTS PASS") {
		t.Fatalf("codex agents did not report PASS: stdout=%q", stdout.String())
	}

	compiled := filepath.Join(filepath.Join(home, ".codex", "agents"), "quirky.toml")
	head := "# Generated by pfm codex build from templates/global/agents/quirky.md" +
		"; do not edit — edit the source, then re-run: pfm codex build\n" +
		"name = \"quirky\"\n" +
		"description = \"Uses \\\"walker fast\\\" and \\\"map it now\\\" verbatim.\"\n" +
		"developer_instructions = \"\"\"\n"
	// The role's own body, escaped byte for byte, is the whole value.
	body := "Body has a literal triple quote \\\"\\\"\\\" and a backslash \\\\ standalone.\n" +
		"\"\"\"\n"
	got, err := os.ReadFile(compiled)
	if err != nil {
		t.Fatalf("read compiled toml: %v", err)
	}
	if string(got) != head+body {
		t.Fatalf("compiled toml =\n%q\nwant %q ... %q", string(got), head, body)
	}

	inClone := filepath.Join(home, ".professor", "templates", "global", "agents", "quirky.toml")
	if _, err := os.Lstat(inClone); !os.IsNotExist(err) {
		t.Fatalf("expected no .toml written inside the source clone at %s, lstat err=%v", inClone, err)
	}

	// Claude reads its agent through a link to the clone; Codex opens its role
	// with O_NOFOLLOW and would refuse one, so the role IS the compiled file.
	claudeAgent := filepath.Join(home, ".claude", "agents", "quirky.md")
	source := filepath.Join(home, ".professor", "templates", "global", "agents", "quirky.md")
	resolved, err := os.Readlink(claudeAgent)
	if err != nil {
		t.Fatalf("readlink %s: %v", claudeAgent, err)
	}
	if filepath.Clean(resolved) != filepath.Clean(source) {
		t.Fatalf("%s -> %s, want -> %s", claudeAgent, resolved, source)
	}
	if info, err := os.Lstat(compiled); err != nil || !info.Mode().IsRegular() {
		t.Fatalf("%s is not the regular role file Codex loads (info=%v err=%v)", compiled, info, err)
	}
}

// TestCodexAgentsCommandRejectsAPositionalArgument matches build/check,
// which both reject anything past a lone optional repo-root; agents takes no
// positional at all since it has no repo root.
func TestCodexAgentsCommandRejectsAPositionalArgument(t *testing.T) {
	jailTest(t)
	var stdout, stderr bytes.Buffer
	if code := run([]string{"codex", "agents", "unexpected"}, &stdout, &stderr); code != 2 {
		t.Fatalf("codex agents with a positional: code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
}

// TestCodexAgentsCommandListedInHelp keeps the action discoverable alongside
// build/check.
func TestCodexAgentsCommandListedInHelp(t *testing.T) {
	jailTest(t)
	var stdout, stderr bytes.Buffer
	if code := run([]string{"codex", "help"}, &stdout, &stderr); code != 0 {
		t.Fatalf("codex help code=%d stdout=%q stderr=%q", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "pfm codex agents") {
		t.Fatalf("codex help does not mention agents: %s", stdout.String())
	}
}
