// Package opencodegen compiles the Claude source tree into OpenCode's native
// project and global surfaces. It is filesystem-only so the command adapter
// remains responsible for argv and exit status.
package opencodegen

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	pfmengine "github.com/rezzminator/professor/pfm/internal/engine"
	"github.com/rezzminator/professor/pfm/internal/paths"
)

// Mode selects whether the compiler may change the filesystem.
type Mode uint8

const (
	ModeBuild Mode = iota
	ModeCheck
	ModeDoctor
)

// Options identifies the repository and the HOME whose Claude commands are
// mirrored into OpenCode's global command registry.
type Options struct {
	Root string
	Home string
	Mode Mode
}

// Result is the operator-visible compiler report.
type Result struct {
	OK        bool
	Warnings  []string
	Problems  []string
	Wrote     int
	Unchanged int
	Deleted   int
	Actions   []Action
}

// Action records a filesystem change build would make. Check and doctor
// return the same plan without applying it.
type Action struct {
	Kind   string
	Path   string
	Target string
}

const (
	actionWrite  = "write"
	actionLink   = "link"
	actionDelete = "delete"
	actionChmod  = "chmod"
	newMarker    = "Generated by pfm opencode build"
	oldMarker    = "Generated by .claude/scripts/build-opencode.mjs"
)

// defaultGeneratedFileMode is the permission every reconcileOpenCodeFile
// write has always used; generatedFile.Mode overrides it per output.
const defaultGeneratedFileMode = os.FileMode(0o644)

type generatedFile struct {
	Path    string
	Content string
	Link    string
	// Mode is the wanted permission bits for a regular-file output. Zero
	// means "use the package default" (0o644) — every existing caller
	// leaves it unset, so this changes nothing until a caller sets it.
	Mode os.FileMode
	// Source is the file a MirrorCopy output copies byte for byte; empty
	// for every compiled output.
	Source string
}

type sourceEntry struct {
	Path     string
	Rel      string
	SkillDir bool
}

// compileOpenCode discovers, renders, validates, and reconciles all OpenCode outputs.
func compileOpenCode(options Options) (Result, error) {
	root, err := resolveOpenCodePath(options.Root, "repository root")
	if err != nil {
		return Result{}, err
	}
	home, err := resolveOpenCodePath(options.Home, "home")
	if err != nil {
		return Result{}, err
	}
	result := Result{Warnings: []string{}, Problems: []string{}}
	outputs := make([]generatedFile, 0)
	add := func(output generatedFile) { outputs = append(outputs, output) }
	problem := func(format string, args ...any) {
		result.Problems = append(result.Problems, fmt.Sprintf(format, args...))
	}
	warn := func(format string, args ...any) {
		result.Warnings = append(result.Warnings, fmt.Sprintf(format, args...))
	}
	// A dangling source skips that one entry: build warns and writes the
	// rest, check and doctor fail. The roster walk and the compile walk visit
	// the same sources, so one seen-set keeps it to one line per path.
	danglingSeen := map[string]bool{}
	dangling := func(path string, err error) {
		if danglingSeen[path] {
			return
		}
		danglingSeen[path] = true
		if options.Mode == ModeBuild {
			warn("DANGLING %s: %v", path, err)
		} else {
			problem("DANGLING %s: %v", path, err)
		}
	}
	// A broken source (unreadable, malformed frontmatter or tools block,
	// no relative path) skips the same way: build warns and writes the rest,
	// check and doctor fail.
	skip := func(format string, args ...any) {
		if options.Mode == ModeBuild {
			warn("SKIP "+format, args...)
		} else {
			problem(format, args...)
		}
	}

	roster := map[string]string{}
	for _, source := range []string{
		filepath.Join(root, ".claude", "commands"),
		filepath.Join(root, "templates", "global", "commands"),
		filepath.Join(home, ".claude", "commands"),
	} {
		discoverOpenCodeCommandRoster(source, roster, problem, dangling)
	}
	projects := discoverOpenCodeProjects(root, problem)
	modelMap, modelMapErr := loadOpenCodeModelMap(root)
	if modelMapErr != nil {
		problem("%v", modelMapErr)
	}
	compileOpenCodeAgents(root, projects, roster, modelMap, add, problem, skip, warn, dangling)
	compileOpenCodeCommands(
		filepath.Join(root, ".claude", "commands"),
		".claude/commands",
		roster,
		filepath.Join(root, ".opencode", "command"),
		add,
		problem,
		skip,
		dangling,
	)
	compileOpenCodeCommands(
		filepath.Join(home, ".claude", "commands"),
		"$HOME/.claude/commands",
		roster,
		filepath.Join(home, ".config", openCodeName(), "command"),
		add,
		problem,
		skip,
		dangling,
	)
	compileOpenCodeSkills(root, add, problem, skip, dangling)
	compileConfig(root, add, problem, warn)
	for _, name := range []string{"LICENSE", "SECURITY.md"} {
		source := filepath.Join(root, name)
		if content, readErr := os.ReadFile(source); readErr == nil {
			add(generatedFile{Path: filepath.Join(root, ".opencode", name), Content: string(content), Source: source})
		} else if !errors.Is(readErr, fs.ErrNotExist) {
			problem("read %s: %v", source, readErr)
		} else {
			warn("missing %s — nothing to mirror into .opencode/%s", source, name)
		}
	}

	if options.Mode == ModeBuild && len(result.Problems) != 0 {
		result.OK = false
		return result, nil
	}
	reconciled := reconcileOpenCode(outputs, options.Mode, root, home)
	result.Warnings = append(result.Warnings, reconciled.Warnings...)
	result.Problems = append(result.Problems, reconciled.Problems...)
	result.Wrote, result.Unchanged, result.Deleted = reconciled.Wrote, reconciled.Unchanged, reconciled.Deleted
	result.Actions = reconciled.Actions
	if options.Mode == ModeCheck || options.Mode == ModeDoctor {
		validateOutputs(outputs, root, &result)
	}
	if options.Mode == ModeDoctor {
		validateDoctorSurfaces(root, home, &result)
	}
	result.OK = len(result.Problems) == 0
	return result, nil
}

func Compile(options Options) (Result, error) { return compileOpenCode(options) }
func BuildOpenCode(options Options) (Result, error) {
	options.Mode = ModeBuild
	return compileOpenCode(options)
}

func CheckOpenCode(options Options) (Result, error) {
	options.Mode = ModeCheck
	return compileOpenCode(options)
}

func DoctorOpenCode(options Options) (Result, error) {
	options.Mode = ModeDoctor
	return compileOpenCode(options)
}

func resolveOpenCodePath(path, label string) (string, error) {
	if path == "" {
		var err error
		if label == "home" {
			path, err = paths.Home()
		} else {
			path, err = filepath.Abs(".")
		}
		if err != nil {
			return "", fmt.Errorf("resolve %s: %w", label, err)
		}
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s %q: %w", label, path, err)
	}
	return filepath.Clean(abs), nil
}

func discoverOpenCodeProjects(root string, problem func(string, ...any)) []string {
	projects := []string{"."}
	entries, err := os.ReadDir(root)
	if err != nil {
		problem("read repository root %s: %v", root, err)
		return projects
	}
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "templates" || entry.Name() == ".claude" || entry.Name() == ".opencode" {
			continue
		}
		if hasRegularFile(filepath.Join(root, entry.Name(), "CLAUDE.md")) {
			projects = append(projects, entry.Name())
		}
	}
	sort.Strings(projects[1:])
	return projects
}

func hasRegularFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

func discoverOpenCodeCommandRoster(
	root string,
	roster map[string]string,
	problem func(string, ...any),
	dangling func(string, error),
) {
	for _, entry := range discoverOpenCodeMarkdown(root, problem, dangling) {
		colon := strings.ReplaceAll(strings.TrimSuffix(filepath.ToSlash(entry.Rel), ".md"), "/", ":")
		flat := openCodeFlatName(entry.Rel)
		if colon != flat {
			roster[colon] = "/" + flat
		}
	}
}

func discoverOpenCodeMarkdown(root string, problem func(string, ...any), dangling func(string, error)) []sourceEntry {
	if _, err := os.Stat(root); errors.Is(err, fs.ErrNotExist) {
		return nil
	} else if err != nil {
		problem("inspect %s: %v", root, err)
		return nil
	}
	entries := []sourceEntry{}
	var walk func(string, string, map[string]bool)
	walk = func(current, relative string, ancestors map[string]bool) {
		physical, err := filepath.EvalSymlinks(current)
		if errors.Is(err, fs.ErrNotExist) {
			dangling(current, err)
			return
		}
		if err != nil {
			problem("resolve %s: %v", current, err)
			return
		}
		if ancestors[physical] {
			problem("command source symlink cycle at %s", current)
			return
		}
		nextAncestors := make(map[string]bool, len(ancestors)+1)
		for key, value := range ancestors {
			nextAncestors[key] = value
		}
		nextAncestors[physical] = true
		items, err := os.ReadDir(current)
		if err != nil {
			problem("read %s: %v", current, err)
			return
		}
		for _, item := range items {
			rel := item.Name()
			if relative != "" {
				rel = filepath.Join(relative, item.Name())
			}
			path := filepath.Join(current, item.Name())
			info, ok := statOpenCodeSource(path, item, problem, dangling)
			if !ok {
				continue
			}
			if info.IsDir() {
				walk(path, rel, nextAncestors)
				continue
			}
			if item.Name() == "SKILL.md" {
				entries = append(entries, sourceEntry{Path: filepath.Dir(path), Rel: filepath.Dir(rel), SkillDir: true})
			} else if strings.HasSuffix(item.Name(), ".md") && item.Name() != "README.md" {
				entries = append(entries, sourceEntry{Path: path, Rel: rel})
			}
		}
	}
	walk(root, "", map[string]bool{})
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	return entries
}

// statOpenCodeSource stats one source entry through its symlinks; a dangling
// symlink goes to dangling, any other failure is a problem.
func statOpenCodeSource(
	path string,
	item fs.DirEntry,
	problem func(string, ...any),
	dangling func(string, error),
) (fs.FileInfo, bool) {
	info, err := os.Stat(path)
	if err == nil {
		return info, true
	}
	if errors.Is(err, fs.ErrNotExist) && item.Type()&os.ModeSymlink != 0 {
		dangling(path, err)
	} else {
		problem("stat %s: %v", path, err)
	}
	return nil, false
}

// discoverOpenCodeAgents lists the top-level `.md` files of one agents
// directory, symlinks resolved; a subdirectory (an archive) is never a role.
func discoverOpenCodeAgents(dir string, problem func(string, ...any), dangling func(string, error)) []sourceEntry {
	items, err := os.ReadDir(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		problem("read %s: %v", dir, err)
		return nil
	}
	entries := []sourceEntry{}
	for _, item := range items {
		if !strings.HasSuffix(item.Name(), ".md") || item.Name() == "README.md" {
			continue
		}
		path := filepath.Join(dir, item.Name())
		info, ok := statOpenCodeSource(path, item, problem, dangling)
		if !ok || !info.Mode().IsRegular() {
			continue
		}
		entries = append(entries, sourceEntry{Path: path, Rel: item.Name()})
	}
	return entries
}

func compileOpenCodeAgents(
	root string,
	projects []string,
	roster map[string]string,
	modelMap map[string]string,
	add func(generatedFile),
	problem, skip, warn func(string, ...any),
	dangling func(string, error),
) {
	seen := map[string]bool{}
	knownServers := openCodeKnownMCPServers(root)
	for _, project := range projects {
		for _, entry := range discoverOpenCodeAgents(filepath.Join(root, project, ".claude", "agents"), problem, dangling) {
			name := strings.TrimSuffix(filepath.Base(entry.Path), ".md")
			if project != "." {
				name += "-" + project
			}
			if seen[name] {
				warn("skip %s — root agent %s owns the registration", filepath.ToSlash(entry.Path), name)
				continue
			}
			seen[name] = true
			compileOpenCodeAgent(root, name, entry.Path, roster, modelMap, knownServers, add, skip, warn)
		}
	}
}

func compileOpenCodeAgent(
	root, name, path string,
	roster map[string]string,
	modelMap map[string]string,
	knownServers []string,
	add func(generatedFile),
	skip, warn func(string, ...any),
) {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		skip("relative path of %s: %v", path, err)
		return
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		skip("read %s: %v", path, err)
		return
	}
	fields, body, parseErr := parseOpenCodeFrontmatter(string(raw))
	if parseErr != nil {
		skip("parse %s: %v", path, parseErr)
		return
	}
	description := swapOpenCodeCommands(strings.TrimSpace(fields["description"]), roster)
	content := "---\n# " + generatedMarker(
		filepath.ToSlash(rel),
	) + "\ndescription: " + quoteOpenCodeYAML(
		description,
	) + "\nmode: " + openCodeAgentMode + "\n"
	alias := strings.TrimSpace(fields["model"])
	if comment := strings.Index(alias, " #"); comment >= 0 {
		alias = strings.TrimSpace(alias[:comment])
	}
	if alias != "" {
		model, ok := modelMap[alias]
		if !ok || strings.TrimSpace(model) == "" {
			warn("unmapped OpenCode model alias %q in %s — model omitted", alias, path)
		} else {
			content += "model: " + strings.TrimSpace(model) + "\n"
		}
	}
	if tools, ok := fields["tools"]; ok {
		toolsBlock, toolsWarnings, toolsErr := renderOpenCodeToolsBlock(path, tools, knownServers)
		if toolsErr != nil {
			skip("tools %s: %v", path, toolsErr)
			return
		}
		for _, toolsWarning := range toolsWarnings {
			warn("%s", toolsWarning)
		}
		content += toolsBlock
	}
	if name == "gitter" {
		content += "permission:\n  bash:\n    \"git *\": allow\n"
	}
	content += "---\n" + agentPreamble(
		name,
	) + swapOpenCodeCommands(
		strings.TrimSpace(body),
		roster,
	) + "\n"
	add(generatedFile{Path: filepath.Join(root, ".opencode", "agent", name+".md"), Content: content})
}

func agentPreamble(name string) string {
	return "You are the " + name + " role in the Professor repo, running as a native OpenCode subagent.\n" +
		"First action: read the repo root AGENTS.md in full — its laws bind you (only gitter may write Git; guarded files are read-only for every subagent) and its § OpenCode adapter maps any Claude-harness mechanic named below. Then execute the protocol below exactly; your mode/task comes from the dispatch prompt.\n" +
		"Stamp every deliverable, report, or verdict you produce with: Executor: opencode-subagent/" + name + "\n\n"
}

func compileOpenCodeCommands(
	sourceRoot, sourceLabel string,
	roster map[string]string,
	outputRoot string,
	add func(generatedFile),
	problem, skip func(string, ...any),
	dangling func(string, error),
) {
	for _, entry := range discoverOpenCodeMarkdown(sourceRoot, problem, dangling) {
		file := entry.Path
		if entry.SkillDir {
			file = filepath.Join(entry.Path, "SKILL.md")
		}
		raw, err := os.ReadFile(file)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				dangling(file, err)
			} else {
				skip("read %s: %v", file, err)
			}
			continue
		}
		fields, body, parseErr := parseOpenCodeFrontmatter(string(raw))
		if parseErr != nil {
			skip("parse %s: %v", file, parseErr)
			continue
		}
		flat := openCodeFlatName(entry.Rel)
		relSource := filepath.ToSlash(filepath.Join(sourceLabel, entry.Rel))
		content := "---\n# " + generatedMarker(
			relSource,
		) + "\ndescription: " + quoteOpenCodeYAML(
			swapOpenCodeCommands(strings.TrimSpace(fields["description"]), roster),
		) + "\n---\n" + swapOpenCodeCommands(
			body,
			roster,
		)
		add(generatedFile{Path: filepath.Join(outputRoot, flat+".md"), Content: content})
	}
}

func compileOpenCodeSkills(
	root string,
	add func(generatedFile),
	problem, skip func(string, ...any),
	dangling func(string, error),
) {
	dir := filepath.Join(root, ".claude", "skills")
	entries, err := os.ReadDir(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return
	}
	if err != nil {
		problem("read %s: %v", dir, err)
		return
	}
	for _, entry := range entries {
		source := filepath.Join(dir, entry.Name())
		info, ok := statOpenCodeSource(source, entry, problem, dangling)
		if !ok || !info.IsDir() {
			continue
		}
		dst := filepath.Join(root, ".opencode", "skills", entry.Name())
		rel, relErr := filepath.Rel(filepath.Dir(dst), source)
		if relErr != nil {
			skip("link %s to %s: %v", dst, source, relErr)
			continue
		}
		add(generatedFile{Path: dst, Link: rel})
	}
}

func validateOutputs(outputs []generatedFile, root string, result *Result) {
	for _, output := range outputs {
		if output.Link != "" || output.Path != filepath.Join(root, ".opencode", "opencode.jsonc") {
			continue
		}
		raw, err := os.ReadFile(output.Path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", output.Path, err))
			continue
		}
		var object map[string]json.RawMessage
		if err := json.Unmarshal(parseOpenCodeJSONC(raw), &object); err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — does not parse (%v)", output.Path, err))
		}
	}
}

func validateDoctorSurfaces(root, home string, result *Result) {
	for _, dir := range []string{
		filepath.Join(root, ".opencode", "agent"),
		filepath.Join(root, ".opencode", "command"),
		filepath.Join(home, ".config", openCodeName(), "command"),
	} {
		entries, err := os.ReadDir(dir)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", dir, err))
			continue
		}
		for _, entry := range entries {
			if !strings.HasSuffix(entry.Name(), ".md") {
				continue
			}
			path := filepath.Join(dir, entry.Name())
			raw, readErr := os.ReadFile(path)
			if readErr != nil {
				result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", path, readErr))
				continue
			}
			fields, _, parseErr := parseOpenCodeFrontmatter(string(raw))
			if parseErr != nil {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf("INVALID %s — frontmatter does not parse (%v)", path, parseErr),
				)
				continue
			}
			if strings.Trim(strings.TrimSpace(fields["description"]), "\"") == "" {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf(
						"INVALID %s — empty description; OpenCode filters it out and the role/command goes silent",
						path,
					),
				)
			}
			if filepath.Base(dir) == "agent" && fields["mode"] != openCodeAgentMode {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf(
						"INVALID %s — mode %q is not %s; the compiler only emits %s roles",
						path,
						fields["mode"],
						openCodeAgentMode,
						openCodeAgentMode,
					),
				)
			}
		}
	}
}

func openCodeName() string {
	return pfmengine.MustLookup(pfmengine.OpenCode).LongName
}
