// Package opencodegen compiles the Claude source tree into OpenCode's native
// project and global surfaces. It is filesystem-only so the command adapter
// remains responsible for argv and exit status.
package opencodegen

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	pfmengine "github.com/rezzminator/professor/pfm/internal/engine"
	"github.com/rezzminator/professor/pfm/internal/paths"
)

// Mode selects whether the compiler may change the filesystem.
type Mode uint8

const (
	ModeBuild Mode = iota
	ModeCheck
	ModeDoctor
)

// Options identifies the repository and the HOME whose Claude commands are
// mirrored into OpenCode's global command registry.
type Options struct {
	Root string
	Home string
	Mode Mode
}

// Result is the operator-visible compiler report.
type Result struct {
	OK        bool
	Warnings  []string
	Problems  []string
	Wrote     int
	Unchanged int
	Deleted   int
	Actions   []Action
}

// Action records a filesystem change build would make. Check and doctor
// return the same plan without applying it.
type Action struct {
	Kind   string
	Path   string
	Target string
}

const (
	actionWrite  = "write"
	actionLink   = "link"
	actionDelete = "delete"
	actionChmod  = "chmod"
	newMarker    = "Generated by pfm opencode build"
	oldMarker    = "Generated by .claude/scripts/build-opencode.mjs"
)

// defaultGeneratedFileMode is the permission every reconcileOpenCodeFile
// write has always used; generatedFile.Mode overrides it per output.
const defaultGeneratedFileMode = os.FileMode(0o644)

type generatedFile struct {
	Path    string
	Content string
	Link    string
	// Mode is the wanted permission bits for a regular-file output. Zero
	// means "use the package default" (0o644) — every existing caller
	// leaves it unset, so this changes nothing until a caller sets it.
	Mode os.FileMode
}

type sourceEntry struct {
	Path     string
	Rel      string
	SkillDir bool
}

// compileOpenCode discovers, renders, validates, and reconciles all OpenCode outputs.
func compileOpenCode(options Options) (Result, error) {
	root, err := resolveOpenCodePath(options.Root, "repository root")
	if err != nil {
		return Result{}, err
	}
	home, err := resolveOpenCodePath(options.Home, "home")
	if err != nil {
		return Result{}, err
	}
	result := Result{Warnings: []string{}, Problems: []string{}}
	outputs := make([]generatedFile, 0)
	add := func(output generatedFile) { outputs = append(outputs, output) }
	problem := func(format string, args ...any) {
		result.Problems = append(result.Problems, fmt.Sprintf(format, args...))
	}
	warn := func(format string, args ...any) {
		result.Warnings = append(result.Warnings, fmt.Sprintf(format, args...))
	}

	roster := map[string]string{}
	for _, source := range []string{
		filepath.Join(root, ".claude", "commands"),
		filepath.Join(root, "templates", "global", "commands"),
		filepath.Join(home, ".claude", "commands"),
	} {
		discoverOpenCodeCommandRoster(source, roster, problem)
	}
	projects := discoverOpenCodeProjects(root, problem)
	compileOpenCodeAgents(root, projects, roster, add, problem, warn)
	compileOpenCodeCommands(
		filepath.Join(root, ".claude", "commands"),
		".claude/commands",
		roster,
		filepath.Join(root, ".opencode", "command"),
		add,
		problem,
		warn,
	)
	compileOpenCodeCommands(
		filepath.Join(home, ".claude", "commands"),
		"$HOME/.claude/commands",
		roster,
		filepath.Join(home, ".config", openCodeName(), "command"),
		add,
		problem,
		warn,
	)
	compileOpenCodeSkills(root, add, problem)
	compileConfig(root, add, problem, warn)
	for _, name := range []string{"LICENSE", "SECURITY.md"} {
		source := filepath.Join(root, name)
		if content, readErr := os.ReadFile(source); readErr == nil {
			add(generatedFile{Path: filepath.Join(root, ".opencode", name), Content: string(content)})
		} else if !errors.Is(readErr, fs.ErrNotExist) {
			problem("read %s: %v", source, readErr)
		} else {
			warn("missing %s — nothing to mirror into .opencode/%s", source, name)
		}
	}

	if options.Mode == ModeBuild && len(result.Problems) != 0 {
		result.OK = false
		return result, nil
	}
	reconciled := reconcileOpenCode(outputs, options.Mode, root, home)
	result.Warnings = append(result.Warnings, reconciled.Warnings...)
	result.Problems = append(result.Problems, reconciled.Problems...)
	result.Wrote, result.Unchanged, result.Deleted = reconciled.Wrote, reconciled.Unchanged, reconciled.Deleted
	result.Actions = reconciled.Actions
	if options.Mode == ModeCheck || options.Mode == ModeDoctor {
		validateOutputs(outputs, root, &result)
	}
	if options.Mode == ModeDoctor {
		validateDoctorSurfaces(root, home, &result)
	}
	result.OK = len(result.Problems) == 0
	return result, nil
}

func Compile(options Options) (Result, error) { return compileOpenCode(options) }
func BuildOpenCode(options Options) (Result, error) {
	options.Mode = ModeBuild
	return compileOpenCode(options)
}

func CheckOpenCode(options Options) (Result, error) {
	options.Mode = ModeCheck
	return compileOpenCode(options)
}

func DoctorOpenCode(options Options) (Result, error) {
	options.Mode = ModeDoctor
	return compileOpenCode(options)
}

func resolveOpenCodePath(path, label string) (string, error) {
	if path == "" {
		var err error
		if label == "home" {
			path, err = paths.Home()
		} else {
			path, err = filepath.Abs(".")
		}
		if err != nil {
			return "", fmt.Errorf("resolve %s: %w", label, err)
		}
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s %q: %w", label, path, err)
	}
	return filepath.Clean(abs), nil
}

func discoverOpenCodeProjects(root string, problem func(string, ...any)) []string {
	projects := []string{"."}
	entries, err := os.ReadDir(root)
	if err != nil {
		problem("read repository root %s: %v", root, err)
		return projects
	}
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "templates" || entry.Name() == ".claude" || entry.Name() == ".opencode" {
			continue
		}
		if hasRegularFile(filepath.Join(root, entry.Name(), "CLAUDE.md")) {
			projects = append(projects, entry.Name())
		}
	}
	sort.Strings(projects[1:])
	return projects
}

func hasRegularFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular()
}

func discoverOpenCodeCommandRoster(root string, roster map[string]string, problem func(string, ...any)) {
	for _, entry := range discoverOpenCodeMarkdown(root, problem) {
		colon := strings.ReplaceAll(strings.TrimSuffix(filepath.ToSlash(entry.Rel), ".md"), "/", ":")
		flat := openCodeFlatName(entry.Rel)
		if colon != flat {
			roster[colon] = "/" + flat
		}
	}
}

func discoverOpenCodeMarkdown(root string, problem func(string, ...any)) []sourceEntry {
	if _, err := os.Stat(root); errors.Is(err, fs.ErrNotExist) {
		return nil
	} else if err != nil {
		problem("inspect %s: %v", root, err)
		return nil
	}
	entries := []sourceEntry{}
	var walk func(string, string, map[string]bool)
	walk = func(current, relative string, ancestors map[string]bool) {
		physical, err := filepath.EvalSymlinks(current)
		if err != nil {
			problem("DANGLING %s: %v", current, err)
			return
		}
		if ancestors[physical] {
			problem("command source symlink cycle at %s", current)
			return
		}
		nextAncestors := make(map[string]bool, len(ancestors)+1)
		for key, value := range ancestors {
			nextAncestors[key] = value
		}
		nextAncestors[physical] = true
		items, err := os.ReadDir(current)
		if err != nil {
			problem("read %s: %v", current, err)
			return
		}
		for _, item := range items {
			rel := item.Name()
			if relative != "" {
				rel = filepath.Join(relative, item.Name())
			}
			path := filepath.Join(current, item.Name())
			info, statErr := os.Stat(path)
			if statErr != nil {
				if os.IsNotExist(statErr) && item.Type()&os.ModeSymlink != 0 {
					problem("DANGLING %s: %v", path, statErr)
				} else {
					problem("stat %s: %v", path, statErr)
				}
				continue
			}
			if info.IsDir() {
				walk(path, rel, nextAncestors)
				continue
			}
			if item.Name() == "SKILL.md" {
				entries = append(entries, sourceEntry{Path: filepath.Dir(path), Rel: filepath.Dir(rel), SkillDir: true})
			} else if strings.HasSuffix(item.Name(), ".md") && item.Name() != "README.md" {
				entries = append(entries, sourceEntry{Path: path, Rel: rel})
			}
		}
	}
	walk(root, "", map[string]bool{})
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	return entries
}

func compileOpenCodeAgents(
	root string,
	projects []string,
	roster map[string]string,
	add func(generatedFile),
	problem, warn func(string, ...any),
) {
	seen := map[string]bool{}
	for _, project := range projects {
		for _, entry := range discoverOpenCodeMarkdown(filepath.Join(root, project, ".claude", "agents"), problem) {
			if entry.SkillDir {
				continue
			}
			name := strings.TrimSuffix(filepath.Base(entry.Path), ".md")
			if project != "." {
				name += "-" + project
			}
			if seen[name] {
				warn("skip %s — root agent %s owns the registration", filepath.ToSlash(entry.Path), name)
				continue
			}
			seen[name] = true
			raw, err := os.ReadFile(entry.Path)
			if err != nil {
				problem("read %s: %v", entry.Path, err)
				continue
			}
			fields, body, parseErr := parseOpenCodeFrontmatter(string(raw))
			if parseErr != nil {
				problem("parse %s: %v", entry.Path, parseErr)
				continue
			}
			rel, _ := filepath.Rel(root, entry.Path)
			description := swapOpenCodeCommands(strings.TrimSpace(fields["description"]), roster)
			content := "---\n# " + generatedMarker(
				filepath.ToSlash(rel),
			) + "\ndescription: " + quoteOpenCodeYAML(
				description,
			) + "\nmode: subagent\n"
			if name == "gitter" {
				content += "permission:\n  bash:\n    \"git *\": allow\n"
			}
			content += "---\n" + agentPreamble(
				name,
				fields["model"],
			) + swapOpenCodeCommands(
				strings.TrimSpace(body),
				roster,
			) + "\n"
			add(generatedFile{Path: filepath.Join(root, ".opencode", "agent", name+".md"), Content: content})
		}
	}
}

func agentPreamble(name, model string) string {
	tier := ""
	if strings.TrimSpace(model) != "" {
		tier = "Model tier: " + strings.TrimSpace(
			model,
		) + " per the fleet prompt § Model Selection — run this host's matching model.\n\n"
	}
	return "You are the " + name + " role in the Professor repo, running as a native OpenCode subagent.\n" +
		"First action: read the repo root AGENTS.md in full — its laws bind you (only gitter may write Git; guarded files are read-only for every subagent) and its § OpenCode adapter maps any Claude-harness mechanic named below. Then execute the protocol below exactly; your mode/task comes from the dispatch prompt.\n" +
		"Stamp every deliverable, report, or verdict you produce with: Executor: opencode-subagent/" + name + "\n\n" + tier
}

func compileOpenCodeCommands(
	sourceRoot, sourceLabel string,
	roster map[string]string,
	outputRoot string,
	add func(generatedFile),
	problem, warn func(string, ...any),
) {
	for _, entry := range discoverOpenCodeMarkdown(sourceRoot, problem) {
		file := entry.Path
		if entry.SkillDir {
			file = filepath.Join(entry.Path, "SKILL.md")
		}
		raw, err := os.ReadFile(file)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				warn("DANGLING %s: %v", filepath.ToSlash(filepath.Join(sourceLabel, entry.Rel)), err)
			} else {
				problem("read %s: %v", file, err)
			}
			continue
		}
		fields, body, parseErr := parseOpenCodeFrontmatter(string(raw))
		if parseErr != nil {
			problem("parse %s: %v", file, parseErr)
			continue
		}
		flat := openCodeFlatName(entry.Rel)
		relSource := filepath.ToSlash(filepath.Join(sourceLabel, entry.Rel))
		content := "---\n# " + generatedMarker(
			relSource,
		) + "\ndescription: " + quoteOpenCodeYAML(
			swapOpenCodeCommands(strings.TrimSpace(fields["description"]), roster),
		) + "\n---\n" + swapOpenCodeCommands(
			body,
			roster,
		)
		add(generatedFile{Path: filepath.Join(outputRoot, flat+".md"), Content: content})
	}
}

func compileOpenCodeSkills(root string, add func(generatedFile), problem func(string, ...any)) {
	dir := filepath.Join(root, ".claude", "skills")
	entries, err := os.ReadDir(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return
	}
	if err != nil {
		problem("read %s: %v", dir, err)
		return
	}
	for _, entry := range entries {
		source := filepath.Join(dir, entry.Name())
		info, statErr := os.Stat(source)
		if statErr != nil {
			problem("DANGLING %s: %v", source, statErr)
			continue
		}
		if !info.IsDir() {
			continue
		}
		dst := filepath.Join(root, ".opencode", "skills", entry.Name())
		rel, relErr := filepath.Rel(filepath.Dir(dst), source)
		if relErr != nil {
			problem("link %s to %s: %v", dst, source, relErr)
			continue
		}
		add(generatedFile{Path: dst, Link: rel})
	}
}

func validateOutputs(outputs []generatedFile, root string, result *Result) {
	for _, output := range outputs {
		if output.Link != "" || output.Path != filepath.Join(root, ".opencode", "opencode.jsonc") {
			continue
		}
		raw, err := os.ReadFile(output.Path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", output.Path, err))
			continue
		}
		var object map[string]json.RawMessage
		if err := json.Unmarshal(parseOpenCodeJSONC(raw), &object); err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — does not parse (%v)", output.Path, err))
		}
	}
}

func validateDoctorSurfaces(root, home string, result *Result) {
	for _, dir := range []string{
		filepath.Join(root, ".opencode", "agent"),
		filepath.Join(root, ".opencode", "command"),
		filepath.Join(home, ".config", openCodeName(), "command"),
	} {
		entries, err := os.ReadDir(dir)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", dir, err))
			continue
		}
		for _, entry := range entries {
			if !strings.HasSuffix(entry.Name(), ".md") {
				continue
			}
			path := filepath.Join(dir, entry.Name())
			raw, readErr := os.ReadFile(path)
			if readErr != nil {
				result.Problems = append(result.Problems, fmt.Sprintf("INVALID %s — read failed (%v)", path, readErr))
				continue
			}
			fields, _, parseErr := parseOpenCodeFrontmatter(string(raw))
			if parseErr != nil {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf("INVALID %s — frontmatter does not parse (%v)", path, parseErr),
				)
				continue
			}
			if strings.Trim(strings.TrimSpace(fields["description"]), "\"") == "" {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf(
						"INVALID %s — empty description; OpenCode filters it out and the role/command goes silent",
						path,
					),
				)
			}
			if filepath.Base(dir) == "agent" && fields["mode"] != "subagent" {
				result.Problems = append(
					result.Problems,
					fmt.Sprintf(
						"INVALID %s — mode %q is not subagent; the compiler only emits subagent roles",
						path,
						fields["mode"],
					),
				)
			}
		}
	}
}

func openCodeName() string {
	return pfmengine.MustLookup(pfmengine.OpenCode).LongName
}
