package installer

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (installer *engine) claudeConfigDirs() []string {
	if installer.options.ConfigDirs != nil {
		return installer.options.ConfigDirs
	}
	return []string{installer.options.ConfigDir}
}

// seatConfigDirs returns the directories launched Claude seats actually read.
// claudeConfigDirs instead preserves the configured account-root roster used by
// migrations and fanout, which may omit the implicit seat's real config dir.
func (installer *engine) seatConfigDirs() []string {
	dirs := make([]string, 0, len(installer.options.ConfigDirs)+1)
	dirs = append(dirs, installer.options.ConfigDir)
	dirs = append(dirs, installer.options.ConfigDirs...)
	return dedupePhysicalDirs(dirs)
}

func dedupePhysicalDirs(dirs []string) []string {
	seen := make(map[string]bool, len(dirs))
	result := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		if strings.TrimSpace(dir) == "" {
			continue
		}
		dir = filepath.Clean(dir)
		physical := dir
		if resolved, err := filepath.EvalSymlinks(dir); err == nil {
			physical = filepath.Clean(resolved)
		}
		if seen[physical] {
			continue
		}
		seen[physical] = true
		result = append(result, dir)
	}
	return result
}

func (installer *engine) retireRenamedCodexAgents() error {
	for _, home := range installer.codexHomes() {
		for _, name := range retiredGlobalAgents {
			path := filepath.Join(home, "agents", name+".toml")
			content, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			if err != nil {
				return fmt.Errorf("read retired Codex agent %s: %w", path, err)
			}
			first, _, _ := strings.Cut(string(content), "\n")
			if !strings.HasPrefix(first, "# Generated by pfm codex build from ") &&
				!strings.HasPrefix(first, "# Generated by .claude/scripts/build-codex.mjs") {
				installer.skip(path + " is not a generated agent; preserved")
				continue
			}
			if err := installer.retire(path, "renamed global agent"); err != nil {
				return err
			}
		}
	}
	return nil
}
