package installer

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (installer *engine) claudeConfigDirs() []string {
	dirs := make([]string, 0, len(installer.options.ConfigDirs)+1)
	dirs = append(dirs, installer.options.ConfigDir)
	dirs = append(dirs, installer.options.ConfigDirs...)
	return installer.dedupePhysicalDirs(dirs)
}

// dedupePhysicalDirs collapses the configured account directories to one
// entry per physical path, keeping the logical spelling. A directory whose
// physical path cannot be resolved is KEPT under its logical name and the
// failure is reported through this run's own transcript — once per directory,
// not once per call: the diagnostic used to go to raw os.Stderr, which
// bypassed the Report counts and the activity ledger entirely and printed
// twice for every `--yes` run, because preflight plans the identical pass
// with its stdout discarded.
func (installer *engine) dedupePhysicalDirs(dirs []string) []string {
	seen := make(map[string]bool, len(dirs))
	result := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		if strings.TrimSpace(dir) == "" {
			continue
		}
		dir = filepath.Clean(dir)
		physical := dir
		if resolved, err := filepath.EvalSymlinks(dir); err == nil {
			physical = filepath.Clean(resolved)
		} else if !installer.reportedConfigDirs[dir] {
			if installer.reportedConfigDirs == nil {
				installer.reportedConfigDirs = map[string]bool{}
			}
			installer.reportedConfigDirs[dir] = true
			installer.skip("resolve config directory " + dir + ": " + err.Error())
		}
		if seen[physical] {
			continue
		}
		seen[physical] = true
		result = append(result, dir)
	}
	return result
}

func (installer *engine) retireRenamedCodexAgents() error {
	for _, home := range installer.codexHomes() {
		for _, name := range retiredGlobalAgents {
			path := filepath.Join(home, "agents", name+".toml")
			content, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			if err != nil {
				return fmt.Errorf("read retired Codex agent %s: %w", path, err)
			}
			first, _, _ := strings.Cut(string(content), "\n")
			if !strings.HasPrefix(first, "# Generated by pfm codex build from ") &&
				!strings.HasPrefix(first, "# Generated by .claude/scripts/build-codex.mjs") {
				installer.skip(path + " is not a generated agent; preserved")
				continue
			}
			if err := installer.retire(path, "renamed global agent"); err != nil {
				return err
			}
		}
	}
	return nil
}
