package installer

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (installer *engine) claudeConfigDirs() []string {
	if installer.options.ConfigDirs != nil {
		return installer.options.ConfigDirs
	}
	return []string{installer.options.ConfigDir}
}

func (installer *engine) retireRenamedCodexAgents() error {
	for _, home := range installer.codexHomes() {
		for _, name := range retiredGlobalAgents {
			path := filepath.Join(home, "agents", name+".toml")
			content, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			if err != nil {
				return fmt.Errorf("read retired Codex agent %s: %w", path, err)
			}
			first, _, _ := strings.Cut(string(content), "\n")
			if !strings.HasPrefix(first, "# Generated by pfm codex build from ") &&
				!strings.HasPrefix(first, "# Generated by .claude/scripts/build-codex.mjs") {
				installer.skip(path + " is not a generated agent; preserved")
				continue
			}
			if err := installer.retire(path, "renamed global agent"); err != nil {
				return err
			}
		}
	}
	return nil
}
