package installer

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestUninstallCodexCommandReconciliationNeverWritesANewMirrorEntry pins the
// distinction between "retire what we own" and "recompile whatever remains":
// reconcileCodexCommands must never WRITE a fresh Codex prompt mirror for a
// command that merely happens to still be sitting in ~/.claude/commands at
// uninstall time — a leftover of this installer's own teardown ordering, or
// simply a user's foreign command sharing the directory. Before this fix,
// the real (apply) reconciliation call scanned $HOME/.claude/commands
// directly regardless of installer mode, so any command still there when
// uninstall reached this step got a brand-new Codex mirror entry written for
// it, mid-teardown — the opposite of what uninstalling means.
func TestUninstallCodexCommandReconciliationNeverWritesANewMirrorEntry(t *testing.T) {
	t.Parallel()
	home := t.TempDir()
	// A command this installer never wired and never mirrored — present only
	// because it happens to still be sitting in ~/.claude/commands when
	// uninstall's reconciliation step runs.
	writeFixture(t, filepath.Join(home, ".claude", "commands", "adhoc.md"), "# adhoc\n\nDo the thing.\n")

	installer := &engine{
		options:     Options{Mode: ModeUninstall, Home: home, Stdout: io.Discard},
		apply:       true,
		managedRoot: managedRootForHome(home),
	}
	if err := installer.reconcileCodexCommands(nil); err != nil {
		t.Fatal(err)
	}
	mirrored := filepath.Join(home, ".codex", "prompts", "adhoc.md")
	if _, err := os.Stat(mirrored); !os.IsNotExist(err) {
		t.Fatalf(
			"uninstall's Codex command reconciliation wrote a fresh mirror entry for an unwired command: %s (stat err=%v)",
			mirrored,
			err,
		)
	}
}

// TestInstallCodexCommandReconciliationStillMirrorsCommands is the control:
// the same reconciliation call during a normal apply (not uninstall) must
// still mirror whatever is present — the uninstall-only empty-source
// redirection must not leak into install.
func TestInstallCodexCommandReconciliationStillMirrorsCommands(t *testing.T) {
	t.Parallel()
	home := t.TempDir()
	writeFixture(t, filepath.Join(home, ".claude", "commands", "adhoc.md"), "# adhoc\n\nDo the thing.\n")

	installer := &engine{
		options:     Options{Mode: ModeApply, Home: home, Stdout: io.Discard},
		apply:       true,
		managedRoot: managedRootForHome(home),
	}
	if err := installer.reconcileCodexCommands(nil); err != nil {
		t.Fatal(err)
	}
	mirrored := filepath.Join(home, ".codex", "prompts", "adhoc.md")
	if _, err := os.Stat(mirrored); err != nil {
		t.Fatalf("install's Codex command reconciliation did not mirror the command: %s (stat err=%v)", mirrored, err)
	}
}

// TestInstallReconcilesGlobalCodexCommands is the issue-6 regression: install
// wired the global Claude command sources but never rebuilt their Codex prompt
// and skill mirrors, leaving pfm codex check to report stale/missing/orphans.
func TestInstallReconcilesGlobalCodexCommands(t *testing.T) {
	home := t.TempDir()
	repository := t.TempDir()
	repositorySentinel := filepath.Join(repository, "AGENTS.md")
	writeFixture(t, repositorySentinel, "repository sentinel\n")
	t.Chdir(repository)
	if _, err := Run(context.Background(), Options{
		Mode: ModeDryRun, Home: home, Runner: &fakeRunner{},
	}); err != nil {
		t.Fatalf("dry run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(home, ".codex")); !os.IsNotExist(err) {
		t.Fatalf("dry run created Codex registry: %v", err)
	}
	if _, err := Run(context.Background(), Options{
		Mode: ModeApply, Home: home, Runner: &fakeRunner{},
	}); err != nil {
		t.Fatalf("apply: %v", err)
	}

	for _, path := range []string{
		filepath.Join(home, ".codex", "prompts", "reload.md"),
		filepath.Join(home, ".codex", "skills", "reload", "SKILL.md"),
	} {
		content := readFixture(t, path)
		if !strings.Contains(content, "Generated by pfm codex build") {
			t.Fatalf("global Codex command mirror %s is not marker-owned:\n%s", path, content)
		}
	}
	// The retired /chat: commands never reach ~/.claude/commands/chat/ at all,
	// so their former Codex mirrors (chat-inject, chat-interrogate) must not
	// exist either.
	for _, path := range []string{
		filepath.Join(home, ".codex", "prompts", "chat-inject.md"),
		filepath.Join(home, ".codex", "prompts", "chat-interrogate.md"),
		filepath.Join(home, ".codex", "skills", "chat-inject"),
		filepath.Join(home, ".codex", "skills", "chat-interrogate"),
	} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("retired /chat: command left a Codex mirror at %s: %v", path, err)
		}
	}

	foreign := filepath.Join(home, ".codex", "prompts", "operator.md")
	writeFixture(t, foreign, "operator-owned prompt\n")
	if _, err := Run(context.Background(), Options{
		Mode: ModeUninstall, Home: home, Runner: &fakeRunner{},
	}); err != nil {
		t.Fatalf("uninstall: %v", err)
	}
	for _, path := range []string{
		filepath.Join(home, ".codex", "prompts", "reload.md"),
		filepath.Join(home, ".codex", "skills", "reload"),
	} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("uninstall left marker-owned command mirror %s: %v", path, err)
		}
	}
	if got := readFixture(t, foreign); got != "operator-owned prompt\n" {
		t.Fatalf("uninstall changed foreign prompt: %q", got)
	}
	if got := readFixture(t, repositorySentinel); got != "repository sentinel\n" {
		t.Fatalf("global install path changed repository file: %q", got)
	}
}
