#!/usr/bin/env node
// build-codex.mjs — compile every Codex artifact from the Claude sources of truth.
//
// Sources (hand-edited, NEVER written by this script):
//   CLAUDE.md + <project>/CLAUDE.md      → AGENTS.md sibling of each
//   .claude/agents/*.md                  → .codex/agents/{name}.toml
//   <project>/.claude/agents/*.md        → .codex/agents/{name}-{proj}.toml
//                                          (a roster project's own agent dir; the
//                                          CLAUDE.md there is conventions, not a role)
//   .claude/commands/**/*.md             → .codex/skills/{flat-name}/SKILL.md
//   .claude/commands/**/SKILL.md         → .codex/skills/{flat-name} (dir symlink)
//   .claude/skills/*/                    → .codex/skills/{name} (dir symlink)
//   $HOME/.claude/commands/**/*.md       → $HOME/.codex/skills/ + $HOME/.codex/prompts/
//   .mcp.json                            → .codex/config.toml [mcp_servers] fenced block
//                                          (config.toml stays hand-written; only the fence is managed)
//
// Modes:  generate (default) — write outputs, delete orphans, idempotent
//         check              — report MISSING/STALE/ORPHAN/CONFLICT + doctor, write nothing, exit 1 on any
//         doctor             — check, plus every emitted .toml must PARSE (repo .codex AND
//                              $HOME/.codex, the global tree every seat in every repo reads).
//                              Currency is not validity: a description carrying a raw `"`
//                              compiles to a file that is byte-current and fatal at Codex
//                              startup. No TOML parser reachable → SKIPPED and FAIL, never a pass.
//
// Discovery is dynamic — add/remove/rename any source and the next run follows it;
// nothing here lists files by name. Transforms are pure string operations:
//   verbatim copy + model-alias swap (opus/sonnet/haiku → Codex model names,
//   lowercase word-boundary tokens only, hyphen-guarded so full model IDs survive)
//   + Claude command references rewritten to Codex's own syntax (/name → $name,
//     /flights:orchestrate-nested → $flights-orchestrate-nested); the roster is every name backed by
//     a real .md file under .claude/commands/** — never a hand-written list, never
//     a generic /\w+ rewrite (that would also corrupt path fragments like /scripts,
//     /src, /commands) — so a directory with no {name}.md (e.g. flights/) never yields
//     a bare $flights
//   + in-body CLAUDE.md → AGENTS.md rewrite for the AGENTS.md compile step only
//     (marker line and appended adapter constant keep their own CLAUDE.md wording)
//   + nested command names flattened (flights/orchestrate-nested → flights-orchestrate-nested, name: rewritten)
//   + one constant preamble per agent TOML (Codex subagents receive ONLY
//     developer_instructions — the preamble routes them to AGENTS.md for the law).
// Every generated file carries a marker line; the script only ever overwrites or
// deletes marker-carrying files (or symlinks into .claude trees). Anything else at
// a managed path is a CONFLICT — reported, never touched.

import {
  existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, readlinkSync,
  rmSync, symlinkSync, writeFileSync,
} from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
// Tests and repo-only regeneration can redirect the global-output surface away
// from the live Codex store while preserving the normal installer-facing default.
const HOME = process.env.CODEX_BUILD_HOME ?? process.env.HOME;
const MODE = process.argv[2] ?? 'generate';
if (!['generate', 'check', 'doctor'].includes(MODE)) {
  console.error(`usage: build-codex.mjs [generate|check|doctor]`);
  process.exit(2);
}

const SELF = '.claude/scripts/build-codex.mjs';
// Maps CLAUDE.md § Model Selection's Claude tier aliases to this repo's own
// Codex model names — fill in your actual picks. If § Model Selection also
// names a {FRONTIER_MODEL} alias (a limited-run model above the base `opus`),
// add its literal alias word as a fourth key here (same Codex model as `opus`,
// unless it deserves its own) and extend ALIAS_RE below to match it — nothing
// here discovers it automatically.
const MODEL_MAP = { opus: '{CODEX_MODEL_FRONTIER}', sonnet: '{CODEX_MODEL_SPEC}', haiku: '{CODEX_MODEL_COLLECTOR}' };
// Lowercase alias as a standalone token; hyphen counts as a word char so
// "claude-opus-5" and file names like "walker-fast" never corrupt.
const ALIAS_RE = /(?<![\w-])(opus|sonnet|haiku)(?![\w-])/g;
const swap = (s) => s.replace(ALIAS_RE, (m) => MODEL_MAP[m]);

const marker = (src) => `Generated by ${SELF} from ${src}; do not edit — edit the source, then re-run: node ${SELF}`;
// Files carrying any generation's marker are ours to overwrite/delete — including
// `pfm codex build`'s, which writes these same outputs: not claiming it strands
// every file it wrote as permanently STALE.
const GENERATED_RE = /Generated (by \.claude\/scripts\/build-codex\.mjs|by pfm codex build|from \.professor\/infra)/;

const ADAPTER = `
## Codex adapter — reading this file in the Codex harness

This file is compiled verbatim from CLAUDE.md by ${SELF}; Claude model aliases are already swapped to Codex models ({CODEX_MODEL_FRONTIER} = frontier judgment, {CODEX_MODEL_SPEC} = spec execution, {CODEX_MODEL_COLLECTOR} = collector — add a {FRONTIER_MODEL} row too if CLAUDE.md names one). Where the text names Claude-harness mechanics, map them:

- Agent / Task spawn / \`subagent_type\` → \`spawn_agent\` with the matching \`.codex/agents/*.toml\` role
- AskUserQuestion → ask the user in prose and end your turn
- Workflow() scripts → no equivalent: decompose sequentially or fan out \`spawn_agent\` calls
- Skills / slash commands → \`.codex/skills/{name}/SKILL.md\`, invoked as \`$name\` — Codex has no \`/name\` syntax, so every \`/name\` reference below is already rewritten to \`$name\` (nested Claude names flatten: \`/flights:orchestrate-nested\` → \`$flights-orchestrate-nested\`)
- PreToolUse hooks (guarded files) → Codex has NO hook layer, so the guard is absolute: never edit \`.claude/**\`, any \`CLAUDE.md\`, any \`AGENTS.md\` (generated — change CLAUDE.md and re-run the build) — stop and report instead
- \`make -C {project}\` (the roster entry whose Makefile owns infra) and gitter's git monopoly bind unchanged; \`.codex/rules\` enforces the shell subset
`;

const agentPreamble = (name) => `You are the ${name} role in the {PROJECT_NAME} repo, running as a native Codex subagent.
First action: read the repo root AGENTS.md in full — its laws bind you (gitter's git monopoly, \`make -C {project}\` — the infra-owning roster entry — for all infra ops, no {SUBJECT_NOUN} content outside the access-controlled DB, guarded files are read-only for you) and its § Codex adapter maps any Claude-harness mechanic named below. Then execute the protocol below exactly; your mode/task comes from the dispatch prompt.
Stamp every deliverable, report, or verdict you produce with: Executor: codex-subagent/${name}

`;

// ---------- helpers ----------------------------------------------------------

const read = (p) => readFileSync(p, 'utf8');
const isDir = (p) => existsSync(p) && lstatSync(p).isDirectory();

function* walkMd(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = join(dir, e.name);
    if (e.isDirectory()) yield* walkMd(p);
    else if (e.name === 'SKILL.md') yield { dir: dirname(p), skillDir: true };
    else if (e.name.endsWith('.md') && e.name !== 'README.md') yield { file: p };
  }
}

// Frontmatter: raw lines between the first two `---` fences + naive key: value map.
// YAML block scalars (`key: >` folded, `key: |` literal, optional chomp `-`/`+`)
// consume the indented lines that follow instead of leaving the bare indicator
// as the value; folded joins with spaces, literal joins with newlines.
function parseFm(text) {
  const lines = text.split('\n');
  if (lines[0] !== '---') return { fm: null, body: text, fields: {} };
  const end = lines.indexOf('---', 1);
  if (end === -1) return { fm: null, body: text, fields: {} };
  const fm = lines.slice(1, end);
  const fields = {};
  for (let i = 0; i < fm.length; i++) {
    const block = fm[i].match(/^([A-Za-z-]+):\s*([>|])[-+]?\s*$/);
    if (block) {
      const [, key, style] = block;
      const chunk = [];
      let indent = null;
      while (i + 1 < fm.length) {
        const next = fm[i + 1];
        if (next.trim() === '') { chunk.push(''); i++; continue; }
        const m = next.match(/^(\s+)/);
        if (!m || (indent !== null && m[1].length < indent)) break;
        indent ??= m[1].length;
        chunk.push(next.slice(indent));
        i++;
      }
      while (chunk.length && chunk[chunk.length - 1] === '') chunk.pop();
      fields[key] = chunk.join(style === '>' ? ' ' : '\n');
      continue;
    }
    const m = fm[i].match(/^([A-Za-z-]+):\s*(.*)$/);
    if (m) fields[m[1]] = m[2];
  }
  return { fm, body: lines.slice(end + 1).join('\n'), fields };
}


const flatName = (rel) => rel.replace(/\.md$/, '').split('/').join('-');
const colonName = (rel) => rel.replace(/\.md$/, '').split('/').join(':');
const tomlEscape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const tomlMultiline = (s) => {
  let out = s.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
  if (!out.endsWith('\n')) out += '\n';
  return out;
};

// Codex command-prefix roster — Claude invokes `.claude/commands/**` as `/name`
// (nested dirs join with `:`, e.g. /flights:orchestrate-nested); Codex has no such syntax,
// it invokes the compiled skill as `$name` (nested names flatten with flatName,
// matching the skill dir the command compiles to). The roster is the exact set of
// names backed by a real .md file on disk — never a hand-written list, never a
// generic /\w+ rewrite (that would also mangle path fragments like /scripts, /src,
// /commands). A directory alone (e.g. flights/, no flights.md) contributes no entry, so
// bare /flights must never transform; only its real children (/flights:orchestrate-nested, …) do.
const commandRoster = new Map(); // "name:form" (no leading /) -> "$flat-form"
const commandsRoot = join(ROOT, '.claude/commands');
if (isDir(commandsRoot)) {
  for (const entry of walkMd(commandsRoot)) {
    const rel = relative(commandsRoot, entry.skillDir ? entry.dir : entry.file);
    commandRoster.set(colonName(rel), `$${flatName(rel)}`);
  }
}
// Longest-first alternation: a longer name must win over a roster name that is its
// own prefix at the same text position (JS regex alternation is first-match, not
// longest-match, across `|` branches). Whole-token only: the `/` is not preceded by
// a word char, `/`, `.`, or `-` (protects path fragments); the matched name is not
// followed by a word char, `:`, or `-` (protects an unknown longer/nested token from
// a false partial match).
const CMD_RE = commandRoster.size
  ? new RegExp(`(?<![\\w/.-])/(${[...commandRoster.keys()].sort((a, b) => b.length - a.length).join('|')})(?![\\w:-])`, 'g')
  : null;
const cmdSwap = (s) => (CMD_RE ? s.replace(CMD_RE, (_, name) => commandRoster.get(name)) : s);

// ---------- compile ----------------------------------------------------------
// outputs: absolute path → { content } | { link: target }
const outputs = new Map();
const notes = [];

// Projects = top-level dirs carrying a CLAUDE.md (dynamic; .worktrees etc. have none).
const projects = readdirSync(ROOT, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(join(ROOT, e.name, 'CLAUDE.md')))
  .map((e) => e.name)
  .sort();

// 1) CLAUDE.md → AGENTS.md (root gets the adapter appended)
for (const { src, dst, root } of [
  { src: join(ROOT, 'CLAUDE.md'), dst: join(ROOT, 'AGENTS.md'), root: true },
  ...projects.map((p) => ({ src: join(ROOT, p, 'CLAUDE.md'), dst: join(ROOT, p, 'AGENTS.md'), root: false })),
]) {
  const srcRel = relative(ROOT, src);
  const body = cmdSwap(swap(read(src)).replaceAll('CLAUDE.md', 'AGENTS.md'));
  outputs.set(dst, {
    content: `<!-- ${marker(srcRel)} -->\n${body}${root ? ADAPTER : ''}`,
  });
}

// 2) Agents → .codex/agents/{name}.toml (root name wins a collision — it is the
//    registered wrapper; the child protocol it points at still loads at runtime).
const agentSources = [];
const rootAgentsDir = join(ROOT, '.claude/agents');
if (isDir(rootAgentsDir)) {
  for (const f of readdirSync(rootAgentsDir).filter((n) => n.endsWith('.md')).sort()) {
    agentSources.push({ src: join(rootAgentsDir, f), name: f.replace(/\.md$/, '') });
  }
}
for (const p of projects) {
  const d = join(ROOT, p, '.claude/agents');
  if (!isDir(d)) continue;
  // Suffix = the project's own directory name — a per-project TOML disambiguator.
  // No prefix-stripping convention is assumed; the roster's directory names are
  // whatever the adopter chose.
  const suffix = p;
  for (const f of readdirSync(d).filter((n) => n.endsWith('.md')).sort()) {
    const name = `${f.replace(/\.md$/, '')}-${suffix}`;
    if (agentSources.some((a) => a.name === name)) {
      notes.push(`skip ${p}/.claude/agents/${f} — a prior source already owns ${name}`);
      continue;
    }
    agentSources.push({ src: join(d, f), name });
  }
}
for (const { src, name } of agentSources) {
  const srcRel = relative(ROOT, src);
  const { body, fields } = parseFm(read(src));
  const tools = (fields.tools ?? '').split(',').map((t) => t.trim()).filter(Boolean);
  const readOnly = tools.length > 0 && !tools.some((t) => /^(Write|Edit|MultiEdit|NotebookEdit)$/.test(t));
  const tomlName = name.replace(/-/g, '_');
  const tier = MODEL_MAP[fields.model] ? `# tier: ${MODEL_MAP[fields.model]} (Claude alias: ${fields.model})\n` : '';
  outputs.set(join(ROOT, '.codex/agents', `${name}.toml`), {
    content:
      `# ${marker(srcRel)}\n${tier}name = "${tomlName}"\n` +
      `description = "${tomlEscape(cmdSwap(swap(fields.description ?? '')))}"\n` +
      (readOnly ? `sandbox_mode = "read-only"\n` : '') +
      `developer_instructions = """\n${tomlMultiline(agentPreamble(tomlName) + cmdSwap(swap(body.trim())))}"""\n`,
  });
}

// 3) Commands → skills. One transform for repo and global; SKILL.md-shaped dirs symlink.
function compileCommands(srcRoot, srcLabel, emit) {
  if (!isDir(srcRoot)) return;
  for (const entry of walkMd(srcRoot)) {
    if (entry.skillDir) {
      emit({ flat: flatName(relative(srcRoot, entry.dir)), linkTo: entry.dir });
      continue;
    }
    const rel = relative(srcRoot, entry.file);
    const flat = flatName(rel);
    const raw = read(entry.file);
    const { fm, body, fields } = parseFm(raw);
    const fmLines = (fm ?? []).filter((l) => !/^name:/.test(l));
    const content =
      `---\n# ${marker(`${srcLabel}/${rel}`)}\nname: ${flat}\n${cmdSwap(fmLines.join('\n'))}\n---\n${cmdSwap(swap(body))}`;
    emit({ flat, content, modelInvocable: fields['disable-model-invocation'] !== 'true' });
  }
}

compileCommands(join(ROOT, '.claude/commands'), '.claude/commands', (o) => {
  const dst = join(ROOT, '.codex/skills', o.flat);
  if (o.linkTo) outputs.set(dst, { link: relative(dirname(dst), o.linkTo) });
  else outputs.set(join(dst, 'SKILL.md'), { content: o.content });
});

// Repo skill dirs → true symlinks (a symlinked skill DIRECTORY loads; keep zero generated bytes).
const skillsDir = join(ROOT, '.claude/skills');
if (isDir(skillsDir)) {
  for (const s of readdirSync(skillsDir).sort()) {
    if (!isDir(join(skillsDir, s))) continue;
    const dst = join(ROOT, '.codex/skills', s);
    outputs.set(dst, { link: relative(dirname(dst), join(skillsDir, s)) });
  }
}

// Global: $HOME/.claude/commands → $HOME/.codex. Prompts always (user-invoked /name);
// skills only for model-invocable commands (a side-effect command must not auto-route).
compileCommands(join(HOME, '.claude/commands'), '$HOME/.claude/commands', (o) => {
  if (o.linkTo) {
    outputs.set(join(HOME, '.codex/skills', o.flat), { link: o.linkTo });
    return;
  }
  outputs.set(join(HOME, '.codex/prompts', `${o.flat}.md`), { content: o.content });
  if (o.modelInvocable) outputs.set(join(HOME, '.codex/skills', o.flat, 'SKILL.md'), { content: o.content });
});

// ---------- reconcile --------------------------------------------------------

function isLink(p) {
  try { return lstatSync(p).isSymbolicLink(); } catch { return false; }
}
const claimable = (p) => {
  if (isLink(p)) return true;
  if (!existsSync(p)) return true;
  const st = lstatSync(p);
  if (st.isFile()) return GENERATED_RE.test(read(p).slice(0, 600));
  if (st.isDirectory()) {
    const sk = join(p, 'SKILL.md');
    return existsSync(sk) && GENERATED_RE.test(read(sk).slice(0, 600));
  }
  return false;
};

const problems = [];
let wrote = 0, unchanged = 0, deleted = 0;

for (const [dst, out] of [...outputs.entries()].sort()) {
  if (out.link) {
    if (isLink(dst) && readlinkSync(dst) === out.link) { unchanged++; continue; }
    if (MODE !== 'generate') { problems.push(`${isLink(dst) || existsSync(dst) ? 'STALE ' : 'MISSING'} ${dst} (want symlink → ${out.link})`); continue; }
    if (!claimable(dst)) { problems.push(`CONFLICT ${dst} — exists without a generated marker; not touching it`); continue; }
    rmSync(dst, { recursive: true, force: true });
    mkdirSync(dirname(dst), { recursive: true });
    symlinkSync(out.link, dst);
    wrote++;
  } else {
    const current = existsSync(dst) && !isLink(dst) && lstatSync(dst).isFile() ? read(dst) : null;
    if (current === out.content) { unchanged++; continue; }
    if (MODE !== 'generate') { problems.push(`${current === null ? 'MISSING' : 'STALE '} ${dst}`); continue; }
    if (!claimable(dst)) { problems.push(`CONFLICT ${dst} — exists without a generated marker; not touching it`); continue; }
    if (isLink(dst)) rmSync(dst);
    mkdirSync(dirname(dst), { recursive: true });
    writeFileSync(dst, out.content);
    wrote++;
  }
}

// Regression pin: `description = ">"` / `"|"` is the literal signature of the
// block-scalar frontmatter bug (the fold/literal indicator captured as the whole
// value instead of its continuation lines) — check mode fails loudly if it recurs.
if (MODE !== 'generate') {
  for (const [dst, out] of outputs) {
    if (out.content && /^description = "[>|]"$/m.test(out.content)) {
      problems.push(`BUG-SIGNATURE ${dst} — description compiled to the bare block-scalar indicator; frontmatter parser regressed`);
    }
  }
}

// MCP servers — managed fence inside .codex/config.toml (hand-written keeper; only
// the fenced region is generated). Repo .mcp.json is the source; stdio fields map
// 1:1 (command/args/env), remote servers map url; unmapped fields are noted, never
// silently dropped. A server hand-defined OUTSIDE the fence that also appears in
// .mcp.json is a CONFLICT (a duplicate TOML table would be invalid) — delete one.
// No .mcp.json (or an emptied one) removes the fence. $HOME-level MCP registries
// are not covered.
const MCP_BEGIN = `# BEGIN mcp_servers — generated by ${SELF} from .mcp.json; do not edit inside this fence`;
const MCP_END = '# END mcp_servers — generated';
const tomlKey = (k) => (/^[A-Za-z0-9_-]+$/.test(k) ? k : `"${tomlEscape(k)}"`);
const tomlStr = (s) => `"${tomlEscape(String(s))}"`;
{
  const cfgPath = join(ROOT, '.codex/config.toml');
  const mcpPath = join(ROOT, '.mcp.json');
  const current = existsSync(cfgPath) ? read(cfgPath) : '';
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const fenceRe = new RegExp(`\\n?${esc(MCP_BEGIN)}[\\s\\S]*?${esc(MCP_END)}\\n?`);
  const hand = current.replace(fenceRe, '\n');
  let desired = hand;
  if (existsSync(mcpPath)) {
    const servers = JSON.parse(read(mcpPath)).mcpServers ?? {};
    const handNames = new Set(
      [...hand.matchAll(/^\[mcp_servers\.([^\]]+)\]/gm)].map((m) => m[1].replace(/^"|"$/g, '')),
    );
    const blocks = [];
    for (const name of Object.keys(servers).sort()) {
      if (handNames.has(name)) {
        problems.push(`CONFLICT ${cfgPath} — [mcp_servers.${name}] is hand-defined outside the generated fence AND in .mcp.json; delete one of the two`);
        continue;
      }
      const s = servers[name];
      const lines = [`[mcp_servers.${tomlKey(name)}]`];
      if (s.command) lines.push(`command = ${tomlStr(s.command)}`);
      if (Array.isArray(s.args) && s.args.length) lines.push(`args = [${s.args.map(tomlStr).join(', ')}]`);
      if (s.url) lines.push(`url = ${tomlStr(s.url)}`);
      if (s.env && Object.keys(s.env).length) {
        lines.push(`env = { ${Object.keys(s.env).sort().map((k) => `${tomlKey(k)} = ${tomlStr(s.env[k])}`).join(', ')} }`);
      }
      const unmapped = Object.keys(s).filter((k) => !['command', 'args', 'env', 'url', 'type'].includes(k));
      if (unmapped.length) notes.push(`mcp ${name}: fields not mapped to codex config: ${unmapped.join(', ')}`);
      blocks.push(lines.join('\n'));
    }
    if (blocks.length) desired = `${hand.replace(/\n*$/, '\n')}\n${MCP_BEGIN}\n${blocks.join('\n\n')}\n${MCP_END}\n`;
  }
  if (desired !== current) {
    if (MODE !== 'generate') problems.push(`STALE  ${cfgPath} (mcp_servers fence out of date with .mcp.json)`);
    else { writeFileSync(cfgPath, desired); wrote++; }
  } else { unchanged++; }
}

// Orphans: managed dirs may only hold computed outputs. A marker-carrying file/dir
// or a symlink into a .claude tree is ours to delete; anything else is left, loudly.
const managedDirs = [
  join(ROOT, '.codex/agents'), join(ROOT, '.codex/skills'),
  join(HOME, '.codex/skills'), join(HOME, '.codex/prompts'),
];
// The managed-dir entry each output occupies (the skill DIR for nested SKILL.md paths).
const wanted = new Set();
for (const p of outputs.keys()) {
  for (const d of managedDirs) {
    if (dirname(p) === d) wanted.add(p);
    else if (dirname(dirname(p)) === d) wanted.add(dirname(p));
  }
}
for (const d of managedDirs) {
  if (!isDir(d)) continue;
  for (const e of readdirSync(d).sort()) {
    const p = join(d, e);
    if (wanted.has(p)) continue;
    const ours = isLink(p) ? readlinkSync(p).includes('.claude/') : claimable(p) && existsSync(p);
    if (!ours) { notes.push(`unmanaged ${p} — no generated marker, leaving it alone`); continue; }
    if (MODE !== 'generate') { problems.push(`ORPHAN ${p} — no source compiles here anymore`); continue; }
    rmSync(p, { recursive: true, force: true });
    deleted++;
  }
}

// ---------- doctor: the artifacts must PARSE, not merely be current ----------
// `check` proves every output is byte-identical to what its source compiles to.
// It cannot see whether those bytes form a valid TOML document: a description
// carrying a raw `"` produces a file that is current, correct-looking, and fatal
// at Codex startup. It also never looked at $HOME/.codex/agents — the global
// tree EVERY seat reads, in every repo — so a break there passed CHECK PASS in
// all of them at once.
//
// Coverage is declared, never assumed. With no TOML parser reachable this
// reports SKIPPED and fails: an instrument that cannot look must never report
// clean, because "nothing found" and "could not look" are different claims.
function runDoctor(problems) {
  const tomls = [];
  const collect = (dir) => {
    if (!isDir(dir)) return;
    for (const e of readdirSync(dir).sort()) {
      const p = join(dir, e);
      if (isDir(p)) collect(p);
      else if (e.endsWith('.toml')) tomls.push(p);
    }
  };
  collect(join(ROOT, '.codex'));
  if (HOME) collect(join(HOME, '.codex'));

  if (!tomls.length) {
    problems.push('DOCTOR SKIPPED — no .toml artifacts found to validate (expected at least .codex/config.toml)');
    return 0;
  }

  const script = 'import sys,tomllib\n' +
    'for f in sys.argv[1:]:\n' +
    '    try:\n' +
    '        tomllib.load(open(f,"rb"))\n' +
    '    except Exception as exc:\n' +
    '        print(f"{f}\\t{exc}")\n';
  let out;
  try {
    out = execFileSync('python3', ['-c', script, ...tomls], { encoding: 'utf8' });
  } catch (err) {
    problems.push(
      `DOCTOR SKIPPED — cannot validate ${tomls.length} TOML artifact(s): no working python3/tomllib ` +
      `(${String(err.message).split('\n')[0]}). Install python3.11+ or validate by hand; this is NOT a pass.`,
    );
    return 0;
  }
  for (const line of out.split('\n').filter(Boolean)) {
    const [file, ...rest] = line.split('\t');
    problems.push(`UNPARSEABLE ${file} — ${rest.join(' ')}`);
  }
  return tomls.length;
}

let doctored = 0;
if (MODE !== 'generate') doctored = runDoctor(problems);

// ---------- report -----------------------------------------------------------

for (const n of notes) console.log(`note: ${n}`);
if (doctored) console.log(`doctor: ${doctored} TOML artifact(s) parsed (repo .codex + $HOME/.codex)`);
const counts = `${outputs.size} outputs (${projects.length + 1} AGENTS.md, ${agentSources.length} agent TOMLs) + config.toml mcp fence — coverage: repo commands+skills+agents, $HOME commands, repo .mcp.json; NOT covered: <project>/.claude/skills, workflows, hooks (Claude-harness-only), $HOME-level MCP registries`;
if (problems.length) {
  for (const p of problems) console.error(p);
  console.error(`${MODE === 'generate' ? 'GENERATE INCOMPLETE' : MODE.toUpperCase() + ' FAIL'} — ${problems.length} problem(s); ${counts}`);
  process.exit(1);
}
console.log(MODE !== 'generate'
  ? `${MODE.toUpperCase()} PASS — ${counts}; ${unchanged} verified current`
  : `generated — ${wrote} written, ${unchanged} unchanged, ${deleted} orphans removed; ${counts}`);
