package codexgen

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/rezzminator/professor/pfm/internal/paths"
)

const variantSourceAgent = "---\nname: lead\ndescription: >\n  Folded lead description\n  over two lines.\ntools: Read, Agent\n" +
	"model: opus # tier note\neffort: low\n---\n\nLead body, byte for byte.\n\n## Section\n\n\"quoted\" text.\n"

func variantAgentsDir(home string) string {
	return filepath.Join(home, ".professor", "templates", "global", "agents")
}

func TestGlobalAgentVariantOverridesOnlyTheDeclaredFrontmatter(t *testing.T) {
	home := t.TempDir()
	dir := variantAgentsDir(home)
	writeTestFile(t, filepath.Join(dir, "lead.md"), variantSourceAgent)
	writeTestFile(t, filepath.Join(dir, GlobalAgentVariantsFile),
		`{"super-lead":{"from":"lead","description":"It's the \"deep\" lead: more effort.","effort":"medium"}}`)

	variants, err := LoadGlobalAgentVariants(dir, filepath.Join(home, "out"))
	if err != nil {
		t.Fatalf("LoadGlobalAgentVariants: %v", err)
	}
	if len(variants) != 1 || variants[0].Name != "super-lead" || variants[0].From != "lead" {
		t.Fatalf("variants = %#v, want one super-lead from lead", variants)
	}
	if want := filepath.Join(home, "out", "super-lead.md"); variants[0].Path != want {
		t.Fatalf("path = %s, want %s", variants[0].Path, want)
	}
	want := "---\n# Generated by pfm from templates/global/agents/lead.md + variants.json — edit the source\n" +
		"name: super-lead\ndescription: 'It''s the \"deep\" lead: more effort.'\ntools: Read, Agent\n" +
		"model: opus # tier note\neffort: medium\n---\n\nLead body, byte for byte.\n\n## Section\n\n\"quoted\" text.\n"
	if got := string(variants[0].Content); got != want {
		t.Fatalf("rendered variant:\n%q\nwant:\n%q", got, want)
	}
	fields, _, err := parseFrontmatter(string(variants[0].Content))
	if err != nil {
		t.Fatalf("rendered variant does not parse: %v", err)
	}
	if fields["description"] != `It's the "deep" lead: more effort.` {
		t.Fatalf("description round-trip = %q", fields["description"])
	}
}

// A variant's "replace" rewrites its body: each key is text that occurs exactly
// once in the source body, swapped for its value; the frontmatter and every
// other body byte carry through.
func TestGlobalAgentVariantReplaceRewritesTheBodyOnly(t *testing.T) {
	home := t.TempDir()
	dir := variantAgentsDir(home)
	writeTestFile(t, filepath.Join(dir, "lead.md"), variantSourceAgent)
	writeTestFile(t, filepath.Join(dir, GlobalAgentVariantsFile),
		`{"super-lead":{"from":"lead","effort":"medium","replace":{`+
			`"byte for byte":"at depth","## Section":"## Deep section\nwith two lines"}}}`)

	variants, err := LoadGlobalAgentVariants(dir, filepath.Join(home, "out"))
	if err != nil {
		t.Fatalf("LoadGlobalAgentVariants: %v", err)
	}
	want := "---\n# Generated by pfm from templates/global/agents/lead.md + variants.json — edit the source\n" +
		"name: super-lead\ndescription: >\n  Folded lead description\n  over two lines.\ntools: Read, Agent\n" +
		"model: opus # tier note\neffort: medium\n---\n\nLead body, at depth.\n\n" +
		"## Deep section\nwith two lines\n\n\"quoted\" text.\n"
	if got := string(variants[0].Content); got != want {
		t.Fatalf("rendered variant:\n%q\nwant:\n%q", got, want)
	}
}

func TestGlobalAgentVariantsAbsentDeclarationIsNoVariants(t *testing.T) {
	home := t.TempDir()
	writeTestFile(t, filepath.Join(variantAgentsDir(home), "lead.md"), variantSourceAgent)
	variants, err := LoadGlobalAgentVariants(variantAgentsDir(home), filepath.Join(home, "out"))
	if err != nil || variants != nil {
		t.Fatalf("variants = %#v, err = %v; want nil, nil", variants, err)
	}
}

func TestGlobalAgentVariantsMalformedDeclarationsAreNamedErrors(t *testing.T) {
	for name, tc := range map[string]struct{ decl, want string }{
		"unparseable":         {`{"super-lead":`, "parse"},
		"bad name":            {`{"Super_Lead":{"from":"lead"}}`, "kebab-case"},
		"missing from":        {`{"super-lead":{"effort":"medium"}}`, `"from" must name a source agent`},
		"unknown source":      {`{"super-lead":{"from":"ghost"}}`, "read source agent"},
		"collision":           {`{"other":{"from":"lead"}}`, "collides with the original agent"},
		"unknown key":         {`{"super-lead":{"from":"lead","colour":"red"}}`, `no "colour" to override`},
		"non-string":          {`{"super-lead":{"from":"lead","effort":3}}`, "must be a string"},
		"multi-line":          {`{"super-lead":{"from":"lead","effort":"a\nb"}}`, "single line"},
		"name override":       {`{"super-lead":{"from":"lead","name":"x"}}`, "never an override"},
		"variant of other":    {`{"a-lead":{"from":"b-lead"},"b-lead":{"from":"lead"}}`, "itself a variant"},
		"replace not object":  {`{"super-lead":{"from":"lead","replace":"x"}}`, `"replace" must be an object`},
		"replace non-string":  {`{"super-lead":{"from":"lead","replace":{"Lead body":3}}}`, "must be a string"},
		"replace empty":       {`{"super-lead":{"from":"lead","replace":{"":"x"}}}`, "empty"},
		"replace absent":      {`{"super-lead":{"from":"lead","replace":{"ghost text":"x"}}}`, "occurs 0 times"},
		"replace ambiguous":   {`{"super-lead":{"from":"lead","replace":{"byte":"x"}}}`, "occurs 2 times in the body"},
		"replace frontmatter": {`{"super-lead":{"from":"lead","replace":{"tools: Read":"x"}}}`, "occurs 0 times"},
	} {
		t.Run(name, func(t *testing.T) {
			home := t.TempDir()
			dir := variantAgentsDir(home)
			writeTestFile(t, filepath.Join(dir, "lead.md"), variantSourceAgent)
			writeTestFile(t, filepath.Join(dir, "other.md"), variantSourceAgent)
			writeTestFile(t, filepath.Join(dir, GlobalAgentVariantsFile), tc.decl)
			_, err := LoadGlobalAgentVariants(dir, filepath.Join(home, "out"))
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want one containing %q", err, tc.want)
			}
			if _, runErr := RunGlobalAgents(GlobalAgentsOptions{Home: home}); runErr == nil {
				t.Fatalf("RunGlobalAgents accepted a malformed variants declaration")
			}
		})
	}
}

func TestGlobalAgentsRenderLinkAndCompileAVariant(t *testing.T) {
	home := t.TempDir()
	dir := variantAgentsDir(home)
	second := filepath.Join(home, ".cc", "2")
	writeTestFile(t, filepath.Join(dir, "lead.md"), variantSourceAgent)
	writeTestFile(t, filepath.Join(dir, GlobalAgentVariantsFile),
		`{"super-lead":{"from":"lead","description":"Deep lead.","effort":"medium"}}`)
	options := GlobalAgentsOptions{Home: home, ClaudeConfigDirs: []string{filepath.Join(home, ".claude"), second}}
	generatedMD := filepath.Join(paths.GeneratedClaudeAgentsDir(home), "super-lead.md")

	options.Mode = ModeCheck
	plan, err := RunGlobalAgents(options)
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	if _, err := os.Lstat(generatedMD); !os.IsNotExist(err) {
		t.Fatalf("check mode wrote %s (err=%v)", generatedMD, err)
	}
	wroteMD := false
	for _, action := range plan.Actions {
		if action.Kind == actionWrite && action.Path == generatedMD {
			wroteMD = true
		}
	}
	if !wroteMD {
		t.Fatalf("check plan never names the variant write: %#v", plan.Actions)
	}
	for _, config := range options.ClaudeConfigDirs {
		if !hasGlobalAgentLinkAction(plan.Actions, filepath.Join(config, "agents", "super-lead.md"), generatedMD) {
			t.Fatalf("check plan never links the variant into %s: %#v", config, plan.Actions)
		}
	}

	options.Mode = ModeBuild
	if _, err := RunGlobalAgents(options); err != nil {
		t.Fatalf("build: %v", err)
	}
	for _, config := range options.ClaudeConfigDirs {
		assertGlobalSymlink(t, filepath.Join(config, "agents", "super-lead.md"), generatedMD)
		assertGlobalSymlink(t, filepath.Join(config, "agents", "lead.md"), filepath.Join(dir, "lead.md"))
	}
	if _, err := os.Lstat(filepath.Join(home, ".claude", "agents", GlobalAgentVariantsFile)); !os.IsNotExist(err) {
		t.Fatalf("the declaration itself was linked as an agent (err=%v)", err)
	}
	toml := filepath.Join(home, ".codex", "agents", "super-lead.toml")
	assertGlobalRoleFile(t, toml)
	content := string(mustReadTestFile(t, toml))
	if !strings.Contains(content, `name = "super-lead"`) || !strings.Contains(content, `description = "Deep lead."`) ||
		!strings.Contains(content, "Lead body, byte for byte.") {
		t.Fatalf("variant TOML twin:\n%s", content)
	}

	options.Mode = ModeCheck
	settled, err := RunGlobalAgents(options)
	if err != nil {
		t.Fatalf("re-check: %v", err)
	}
	if len(settled.Actions) != 0 || len(settled.Problems) != 0 {
		t.Fatalf("a built host still plans work: actions=%#v problems=%#v", settled.Actions, settled.Problems)
	}
}

// The declaration this repository ships must render: a variants.json that
// drifts from its source agent fails here, not on an adopter's install.
func TestShippedGlobalAgentVariantsRender(t *testing.T) {
	_, testFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	agentsDir := filepath.Join(filepath.Dir(testFile), "..", "..", "..", "templates", "global", "agents")
	variants, err := LoadGlobalAgentVariants(agentsDir, t.TempDir())
	if err != nil {
		t.Fatalf("shipped variants.json: %v", err)
	}
	for _, variant := range variants {
		if _, _, err := renderGlobalAgentTOML(variant.Path, string(variant.Content), t.TempDir()); err != nil {
			t.Fatalf("variant %s does not compile to TOML: %v", variant.Name, err)
		}
	}
}
