package codexgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	mcpBegin       = "# BEGIN mcp_servers — generated by pfm codex build from .mcp.json; do not edit inside this fence"
	legacyMCPBegin = "# BEGIN mcp_servers — generated by .claude/scripts/build-codex.mjs from .mcp.json; do not edit inside this fence"
	mcpEnd         = "# END mcp_servers — generated"
)

type mcpResult struct {
	Content  string
	Notes    []string
	Problems []string
	Changed  bool
}

func compileMCP(root string) (mcpResult, error) {
	configPath := filepath.Join(root, ".codex", "config.toml")
	mcpPath := filepath.Join(root, ".mcp.json")
	currentBytes, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return mcpResult{}, fmt.Errorf("read %s: %w", configPath, err)
	}
	current := string(currentBytes)
	hand := stripMCPFence(current)
	result := mcpResult{Content: hand}
	data, err := os.ReadFile(mcpPath)
	if os.IsNotExist(err) {
		result.Changed = result.Content != current
		return result, nil
	}
	if err != nil {
		return result, fmt.Errorf("read %s: %w", mcpPath, err)
	}
	servers, unmapped, err := decodeMCP(data)
	if err != nil {
		return result, err
	}
	for name, fields := range unmapped {
		if len(fields) != 0 {
			result.Notes = append(
				result.Notes,
				fmt.Sprintf("mcp %s: fields not mapped to codex config: %s", name, strings.Join(fields, ", ")),
			)
		}
	}
	sort.Strings(result.Notes)
	if len(servers) == 0 {
		result.Changed = result.Content != current
		return result, nil
	}
	handNames := map[string]bool{}
	re := regexp.MustCompile(`(?m)^\[mcp_servers\.([^\]]+)\]`)
	for _, match := range re.FindAllStringSubmatch(hand, -1) {
		handNames[strings.Trim(match[1], `"`)] = true
	}
	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)
	blocks := make([]string, 0, len(names))
	for _, name := range names {
		if handNames[name] {
			result.Problems = append(
				result.Problems,
				fmt.Sprintf(
					"CONFLICT %s — [mcp_servers.%s] is hand-defined outside the generated fence AND in .mcp.json",
					configPath,
					name,
				),
			)
			continue
		}
		server := servers[name]
		lines := []string{"[mcp_servers." + tomlKey(name) + "]"}
		if server.Command != "" {
			lines = append(lines, "command = "+tomlString(server.Command))
		}
		if len(server.Args) > 0 {
			values := make([]string, len(server.Args))
			for i, arg := range server.Args {
				values[i] = tomlString(arg)
			}
			lines = append(lines, "args = ["+strings.Join(values, ", ")+"]")
		}
		if server.URL != "" {
			lines = append(lines, "url = "+tomlString(server.URL))
		}
		if len(server.Env) > 0 {
			keys := make([]string, 0, len(server.Env))
			for key := range server.Env {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			values := make([]string, len(keys))
			for i, key := range keys {
				values[i] = tomlKey(key) + " = " + tomlString(server.Env[key])
			}
			lines = append(lines, "env = { "+strings.Join(values, ", ")+" }")
		}
		blocks = append(blocks, strings.Join(lines, "\n"))
	}
	if len(blocks) > 0 {
		result.Content = strings.TrimRight(
			hand,
			"\n",
		) + "\n\n" + mcpBegin + "\n" + strings.Join(
			blocks,
			"\n\n",
		) + "\n" + mcpEnd + "\n"
	}
	result.Changed = result.Content != current
	return result, nil
}

func stripMCPFence(current string) string {
	for _, begin := range []string{mcpBegin, legacyMCPBegin} {
		pattern := regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(begin) + `.*?` + regexp.QuoteMeta(mcpEnd) + `\n?`)
		current = pattern.ReplaceAllString(current, "\n")
	}
	return current
}
