package codexgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	mcpBegin       = "# BEGIN mcp_servers — generated by pfm codex build from .mcp.json; do not edit inside this fence"
	legacyMCPBegin = "# BEGIN mcp_servers — generated by .claude/scripts/build-codex.mjs from .mcp.json; do not edit inside this fence"
	mcpEnd         = "# END mcp_servers — generated"
)

type mcpResult struct {
	Content  string
	Notes    []string
	Problems []string
	Changed  bool
}

func compileMCP(root string) (mcpResult, error) {
	configPath := filepath.Join(root, ".codex", "config.toml")
	mcpPath := filepath.Join(root, ".mcp.json")
	currentBytes, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return mcpResult{}, fmt.Errorf("read %s: %w", configPath, err)
	}
	current := string(currentBytes)
	hand := stripMCPFence(current)
	result := mcpResult{Content: hand, Problems: mcpFenceProblems(current, configPath)}
	data, err := os.ReadFile(mcpPath)
	if os.IsNotExist(err) {
		result.Changed = result.Content != current
		return result, nil
	}
	if err != nil {
		return result, fmt.Errorf("read %s: %w", mcpPath, err)
	}
	servers, unmapped, err := decodeMCP(data)
	if err != nil {
		return result, err
	}
	for name, fields := range unmapped {
		if len(fields) != 0 {
			result.Notes = append(
				result.Notes,
				fmt.Sprintf("mcp %s: fields not mapped to codex config: %s", name, strings.Join(fields, ", ")),
			)
		}
	}
	sort.Strings(result.Notes)
	if len(servers) == 0 {
		result.Changed = result.Content != current
		return result, nil
	}
	handNames := map[string]bool{}
	re := regexp.MustCompile(`(?m)^\[mcp_servers\.([^\]]+)\]`)
	for _, match := range re.FindAllStringSubmatch(hand, -1) {
		handNames[strings.Trim(match[1], `"`)] = true
	}
	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)
	blocks := make([]string, 0, len(names))
	for _, name := range names {
		if handNames[name] {
			result.Problems = append(
				result.Problems,
				fmt.Sprintf(
					"CONFLICT %s — [mcp_servers.%s] is hand-defined outside the generated fence AND in .mcp.json",
					configPath,
					name,
				),
			)
			continue
		}
		server := servers[name]
		lines := []string{"[mcp_servers." + tomlKey(name) + "]"}
		if server.Command != "" {
			lines = append(lines, "command = "+tomlString(server.Command))
		}
		if len(server.Args) > 0 {
			values := make([]string, len(server.Args))
			for i, arg := range server.Args {
				values[i] = tomlString(arg)
			}
			lines = append(lines, "args = ["+strings.Join(values, ", ")+"]")
		}
		if server.URL != "" {
			lines = append(lines, "url = "+tomlString(server.URL))
		}
		if len(server.Env) > 0 {
			keys := make([]string, 0, len(server.Env))
			for key := range server.Env {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			values := make([]string, len(keys))
			for i, key := range keys {
				values[i] = tomlKey(key) + " = " + tomlString(server.Env[key])
			}
			lines = append(lines, "env = { "+strings.Join(values, ", ")+" }")
		}
		blocks = append(blocks, strings.Join(lines, "\n"))
	}
	if len(blocks) > 0 {
		result.Content = strings.TrimRight(
			hand,
			"\n",
		) + "\n\n" + mcpBegin + "\n" + strings.Join(
			blocks,
			"\n\n",
		) + "\n" + mcpEnd + "\n"
	}
	result.Changed = result.Content != current
	return result, nil
}

// mcpFenceProblems scans the untouched `.codex/config.toml` content for a
// malformed mcp_servers fence: an unpaired BEGIN (no matching END), a lone
// END (no preceding BEGIN), or more than one complete fence. stripMCPFence's
// regexp only ever matches a well-formed BEGIN...END pair, so any of these
// shapes previously passed through untouched as "hand" content and a second
// fence got appended beside it with no Problem raised in either build or
// check (L3-F11). Each is now a named Problem; compileMCP's caller already
// skips writing .codex/config.toml whenever Problems is non-empty, so build
// never appends a second fence over a malformed one.
func mcpFenceProblems(current, configPath string) []string {
	var problems []string
	inFence := false
	fences := 0
	for _, line := range strings.Split(current, "\n") {
		switch line {
		case mcpBegin, legacyMCPBegin:
			if inFence {
				problems = append(problems, fmt.Sprintf(
					"CONFLICT %s: a second mcp_servers BEGIN fence starts before the first one's END — hand-fix or remove the stale fence",
					configPath,
				))
				continue
			}
			inFence = true
		case mcpEnd:
			if !inFence {
				problems = append(problems, fmt.Sprintf(
					"CONFLICT %s: an mcp_servers END fence has no matching BEGIN — hand-fix or remove the stale marker",
					configPath,
				))
				continue
			}
			inFence = false
			fences++
		}
	}
	if inFence {
		problems = append(problems, fmt.Sprintf(
			"CONFLICT %s: an mcp_servers BEGIN fence has no matching END — hand-fix or remove the stale marker",
			configPath,
		))
	}
	if fences > 1 {
		problems = append(problems, fmt.Sprintf(
			"CONFLICT %s: %d mcp_servers fences found, want at most one",
			configPath,
			fences,
		))
	}
	return problems
}

func stripMCPFence(current string) string {
	for _, begin := range []string{mcpBegin, legacyMCPBegin} {
		pattern := regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(begin) + `.*?` + regexp.QuoteMeta(mcpEnd) + `\n?`)
		current = pattern.ReplaceAllString(current, "\n")
	}
	return current
}
