package codexgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rezzminator/professor/pfm/internal/atomicfile"
)

const (
	generatedMarker       = "Generated by pfm codex build"
	legacyGeneratedMarker = "Generated by .claude/scripts/build-codex.mjs"
	actionLink            = "link"
	actionWrite           = "write"
	actionChmod           = "chmod"
)

type generatedFile struct {
	Path    string
	Content string
	Link    string
	// ManagedFence allows the compiler to replace only its generated region in
	// an otherwise hand-written keeper such as .codex/config.toml.
	ManagedFence bool
	// Mode is the wanted permission bits for a regular-file output. Zero
	// means "use the package default" (0o644) — every existing caller
	// leaves it unset, so this changes nothing until a caller sets it.
	Mode os.FileMode
}

// defaultGeneratedFileMode is the permission every reconcileFile write has
// always used; generatedFile.Mode overrides it per output.
const defaultGeneratedFileMode = os.FileMode(0o644)

type reconcileResult struct {
	Wrote, Unchanged, Deleted int
	Problems, Warnings        []string
	Actions                   []Action
}

func reconcile(root, home string, outputs []generatedFile, mode Mode, manageGlobal bool) (reconcileResult, error) {
	managed := []string{
		filepath.Join(root, ".codex", "agents"),
		filepath.Join(root, ".codex", "skills"),
		filepath.Join(home, ".codex", "skills"),
		filepath.Join(home, ".codex", "prompts"),
	}
	if !manageGlobal {
		managed = managed[:2]
	}
	return reconcileManaged(outputs, mode, managed)
}

func reconcileManaged(outputs []generatedFile, mode Mode, managed []string) (reconcileResult, error) {
	return reconcileManagedWithClaim(outputs, mode, managed, claimable)
}

func reconcileManagedWithClaim(
	outputs []generatedFile,
	mode Mode,
	managed []string,
	owns func(string) bool,
) (reconcileResult, error) {
	result := reconcileResult{}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	wanted := map[string]bool{}
	for _, output := range outputs {
		wanted[managedEntry(output.Path, managed)] = true
		if output.Link != "" {
			result.reconcileLink(output, mode, owns)
			continue
		}
		result.reconcileFile(output, mode, owns)
	}
	for _, dir := range managed {
		result.reconcileOrphans(dir, wanted, mode, owns)
	}
	return result, nil
}

func managedEntry(path string, managed []string) string {
	for _, root := range managed {
		relative, err := filepath.Rel(root, path)
		if err != nil || relative == "." || relative == ".." ||
			strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
			continue
		}
		first := strings.Split(relative, string(filepath.Separator))[0]
		return filepath.Join(root, first)
	}
	return path
}

func (r *reconcileResult) reconcileLink(output generatedFile, mode Mode, owns func(string) bool) {
	info, err := os.Lstat(output.Path)
	if err == nil && info.Mode()&os.ModeSymlink != 0 {
		link, readErr := os.Readlink(output.Path)
		if readErr == nil && link == output.Link {
			r.Unchanged++
			return
		}
	}
	if mode == ModeCheck {
		if err == nil && !output.ManagedFence && !owns(output.Path) {
			r.Problems = append(
				r.Problems,
				fmt.Sprintf("CONFLICT %s — exists without a generated marker; not touching it", output.Path),
			)
			return
		}
		state := "STALE"
		if os.IsNotExist(err) {
			state = "MISSING"
		}
		r.Problems = append(r.Problems, fmt.Sprintf("%s %s (want symlink → %s)", state, output.Path, output.Link))
		r.Actions = append(r.Actions, Action{Kind: actionLink, Path: output.Path, Target: output.Link})
		return
	}
	if err == nil && !output.ManagedFence && !owns(output.Path) {
		r.Problems = append(
			r.Problems,
			fmt.Sprintf("CONFLICT %s — exists without a generated marker; not touching it", output.Path),
		)
		return
	}
	r.Actions = append(r.Actions, Action{Kind: actionLink, Path: output.Path, Target: output.Link})
	if removeErr := os.RemoveAll(output.Path); removeErr != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("remove %s: %v", output.Path, removeErr))
		return
	}
	if mkdirErr := os.MkdirAll(filepath.Dir(output.Path), 0o755); mkdirErr != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("mkdir %s: %v", output.Path, mkdirErr))
		return
	}
	if linkErr := os.Symlink(output.Link, output.Path); linkErr != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("symlink %s: %v", output.Path, linkErr))
		return
	}
	r.Wrote++
}

func (r *reconcileResult) reconcileFile(output generatedFile, mode Mode, owns func(string) bool) {
	wantMode := output.Mode
	if wantMode == 0 {
		wantMode = defaultGeneratedFileMode
	}
	info, err := os.Lstat(output.Path)
	current := ""
	haveMode := os.FileMode(0)
	if err == nil && info.Mode().IsRegular() {
		haveMode = info.Mode().Perm()
		bytes, readErr := os.ReadFile(output.Path)
		if readErr == nil {
			current = string(bytes)
		}
	}
	// A generated file whose content is already right but whose mode drifted
	// (an operator's chmod, a permission-lossy restore) is not "Unchanged"
	// (L3-F14) — check names it distinctly from STALE/MISSING content, and
	// build fixes it with a chmod rather than rewriting content that was
	// already correct.
	modeOnlyDrift := current == output.Content && err == nil && info.Mode().IsRegular() && haveMode != wantMode
	if current == output.Content && !modeOnlyDrift {
		r.Unchanged++
		return
	}
	if mode == ModeCheck {
		if err == nil && !output.ManagedFence && !owns(output.Path) {
			r.Problems = append(
				r.Problems,
				fmt.Sprintf("CONFLICT %s — exists without a generated marker; not touching it", output.Path),
			)
			return
		}
		if modeOnlyDrift {
			r.Problems = append(
				r.Problems,
				fmt.Sprintf("MODE %s (want %04o, have %04o)", output.Path, wantMode, haveMode),
			)
			r.Actions = append(
				r.Actions,
				Action{Kind: actionChmod, Path: output.Path, Target: fmt.Sprintf("%04o", wantMode)},
			)
			return
		}
		if current == "" {
			r.Problems = append(r.Problems, "MISSING "+output.Path)
		} else {
			r.Problems = append(r.Problems, "STALE "+output.Path)
		}
		r.Actions = append(r.Actions, Action{Kind: actionWrite, Path: output.Path})
		return
	}
	if err == nil && !output.ManagedFence && !owns(output.Path) {
		r.Problems = append(
			r.Problems,
			fmt.Sprintf("CONFLICT %s — exists without a generated marker; not touching it", output.Path),
		)
		return
	}
	if modeOnlyDrift {
		r.Actions = append(
			r.Actions,
			Action{Kind: actionChmod, Path: output.Path, Target: fmt.Sprintf("%04o", wantMode)},
		)
		if chmodErr := os.Chmod(output.Path, wantMode); chmodErr != nil {
			r.Problems = append(r.Problems, fmt.Sprintf("chmod %s: %v", output.Path, chmodErr))
			return
		}
		r.Wrote++
		return
	}
	r.Actions = append(r.Actions, Action{Kind: actionWrite, Path: output.Path})
	if mkdirErr := os.MkdirAll(filepath.Dir(output.Path), 0o755); mkdirErr != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("mkdir %s: %v", output.Path, mkdirErr))
		return
	}
	if writeErr := atomicfile.Write(output.Path, []byte(output.Content), wantMode); writeErr != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("write %s: %v", output.Path, writeErr))
		return
	}
	r.Wrote++
}

func (r *reconcileResult) reconcileOrphans(dir string, wanted map[string]bool, mode Mode, owns func(string) bool) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return
	}
	if err != nil {
		r.Problems = append(r.Problems, fmt.Sprintf("read managed directory %s: %v", dir, err))
		return
	}
	for _, entry := range entries {
		path := filepath.Join(dir, entry.Name())
		if wanted[path] {
			continue
		}
		if !owns(path) {
			continue
		}
		if mode == ModeCheck {
			r.Problems = append(r.Problems, "ORPHAN "+path)
			r.Actions = append(r.Actions, Action{Kind: "delete", Path: path})
			continue
		}
		r.Actions = append(r.Actions, Action{Kind: "delete", Path: path})
		if err := os.RemoveAll(path); err != nil {
			r.Problems = append(r.Problems, fmt.Sprintf("remove orphan %s: %v", path, err))
		} else {
			r.Deleted++
		}
	}
}

// markerClaimable is the stricter ownership rule used for host-global
// reconciliation. A symlink cannot carry the compiler marker, so an unknown
// symlink in ~/.codex is foreign and must survive — UNLESS its target names
// it as one compileGlobalCommands itself would have written: a
// skill-directory command (entry.skillDir in compiler.go) is mirrored into
// .codex/skills/<flat> as a bare symlink into {home}/.claude/commands/<rel>,
// never as a marker-carrying file, so ownership there is decided the same
// way global_unwire.go's ownedGlobalLink decides it for the registry links —
// by the link's TARGET, never a marker it structurally cannot hold. Without
// this, an uninstall that had already removed the source directory
// (unwireGlobalRegistries) left the .codex/skills mirror dangling: the
// registry promise INSTALL.md § Uninstall makes for "every installer-owned
// link" broke at exactly the one link shape a marker cannot reach. Repository
// reconciliation retains its historical, more permissive symlink ownership
// rule through claimable.
func markerClaimable(home string) func(string) bool {
	commandsRoot := filepath.Join(home, ".claude", "commands")
	return func(path string) bool {
		info, err := os.Lstat(path)
		if err != nil {
			return os.IsNotExist(err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			target, readErr := os.Readlink(path)
			if readErr != nil {
				return false
			}
			if !filepath.IsAbs(target) {
				target = filepath.Join(filepath.Dir(path), target)
			}
			target = filepath.Clean(target)
			return target == commandsRoot || strings.HasPrefix(target, commandsRoot+string(filepath.Separator))
		}
		return claimable(path)
	}
}

func claimable(path string) bool {
	info, err := os.Lstat(path)
	if err != nil {
		return os.IsNotExist(err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return true
	}
	if info.Mode().IsRegular() {
		bytes, err := os.ReadFile(path)
		return err == nil && generatedBytes(bytes)
	}
	if info.IsDir() {
		skill := filepath.Join(path, "SKILL.md")
		bytes, err := os.ReadFile(skill)
		return err == nil && generatedBytes(bytes)
	}
	return false
}

func generatedBytes(bytes []byte) bool {
	prefix := string(bytes[:min(len(bytes), 600)])
	return strings.Contains(prefix, generatedMarker) || strings.Contains(prefix, legacyGeneratedMarker)
}
