package statusline

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func writeTranscript(t *testing.T, lines ...string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "11111111-1111-4111-8111-111111111111.jsonl")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// The prompt-cache TTL is refreshed by API requests, and a local slash command
// (/rc, /cost, /compact's receipt …) writes user-typed records without making
// one. A chat that finished at 01:50 and had /rc run at 14:20 was shown
// "💾1h✗9m" — the anchor had jumped to the local command — when the cache had
// been cold for twelve hours. The anchor is the newest record that WAS a
// request: an assistant record, or a user record that is not a local command.
func TestCacheAnchorIgnoresLocalCommandRecords(t *testing.T) {
	path := writeTranscript(
		t,
		`{"type":"user","timestamp":"2026-09-01T23:48:00.000Z","message":{"role":"user","content":"go"}}`,
		`{"type":"assistant","timestamp":"2026-09-01T23:50:00.000Z","message":{"role":"assistant","content":[{"type":"text","text":"done"}]}}`,
		`{"type":"assistant","isSidechain":true,"timestamp":"2026-09-02T03:00:00.000Z","message":{"role":"assistant","content":[]}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:00.000Z","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:00.500Z","message":{"role":"user","content":"<command-name>/rc</command-name>"}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:01.000Z","message":{"role":"user","content":"<local-command-stdout>connecting…</local-command-stdout>"}}`,
	)
	want := time.Date(2026, 9, 1, 23, 50, 0, 0, time.UTC)
	if got := cacheAnchor(path); !got.Equal(want) {
		t.Fatalf(
			"cacheAnchor = %s, want the last assistant record %s (local-command user records must not anchor the TTL)",
			got,
			want,
		)
	}
}

func TestCacheAnchorFollowsTheNewestRequestInAnOpenTurn(t *testing.T) {
	path := writeTranscript(
		t,
		`{"type":"assistant","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"assistant","content":[]}}`,
		`{"type":"user","timestamp":"2026-09-02T10:07:00.000Z","message":{"role":"user","content":[{"type":"tool_result","content":"ok"}]}}`,
	)
	want := time.Date(2026, 9, 2, 10, 7, 0, 0, time.UTC)
	if got := cacheAnchor(path); !got.Equal(want) {
		t.Fatalf("cacheAnchor = %s, want the tool-result request %s", got, want)
	}
	fresh := writeTranscript(t,
		`{"type":"user","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"user","content":"first prompt"}}`,
	)
	if got := cacheAnchor(fresh); !got.Equal(time.Date(2026, 9, 2, 10, 0, 0, 0, time.UTC)) {
		t.Fatalf("a chat with only its first prompt in flight anchors on that prompt, got %s", got)
	}
	if got := cacheAnchor(writeTranscript(t, `{"type":"summary","summary":"nothing"}`)); !got.IsZero() {
		t.Fatalf("a transcript with no request must yield the zero anchor, got %s", got)
	}
}
