package statusline

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func writeTranscript(t *testing.T, lines ...string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "11111111-1111-4111-8111-111111111111.jsonl")
	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// The prompt-cache TTL is refreshed by API requests, and a local slash command
// (/rc, /cost, /compact's receipt …) writes user-typed records without making
// one. A chat that finished at 01:50 and had /rc run at 14:20 was shown
// "💾1h✗9m" — the anchor had jumped to the local command — when the cache had
// been cold for twelve hours. The anchor is the newest record that sent a
// request: a user record — prompt or tool result — that is not a local command.
func TestCacheAnchorIgnoresLocalCommandRecords(t *testing.T) {
	path := writeTranscript(
		t,
		`{"type":"user","timestamp":"2026-09-01T23:48:00.000Z","message":{"role":"user","content":"go"}}`,
		`{"type":"assistant","timestamp":"2026-09-01T23:50:00.000Z","message":{"role":"assistant","content":[{"type":"text","text":"done"}]}}`,
		`{"type":"assistant","isSidechain":true,"timestamp":"2026-09-02T03:00:00.000Z","message":{"role":"assistant","content":[]}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:00.000Z","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:00.500Z","message":{"role":"user","content":"<command-name>/rc</command-name>"}}`,
		`{"type":"user","timestamp":"2026-09-02T12:20:01.000Z","message":{"role":"user","content":"<local-command-stdout>connecting…</local-command-stdout>"}}`,
	)
	want := time.Date(2026, 9, 1, 23, 48, 0, 0, time.UTC)
	if got := cacheAnchor(path).anchor; !got.Equal(want) {
		t.Fatalf(
			"cacheAnchor = %s, want the last request %s (local-command user records must not anchor the TTL)",
			got,
			want,
		)
	}
}

func TestCacheAnchorFollowsTheNewestRequestInAnOpenTurn(t *testing.T) {
	path := writeTranscript(
		t,
		`{"type":"assistant","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"assistant","content":[]}}`,
		`{"type":"user","timestamp":"2026-09-02T10:07:00.000Z","message":{"role":"user","content":[{"type":"tool_result","content":"ok"}]}}`,
	)
	want := time.Date(2026, 9, 2, 10, 7, 0, 0, time.UTC)
	if got := cacheAnchor(path).anchor; !got.Equal(want) {
		t.Fatalf("cacheAnchor = %s, want the tool-result request %s", got, want)
	}
	fresh := writeTranscript(t,
		`{"type":"user","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"user","content":"first prompt"}}`,
	)
	if got := cacheAnchor(fresh).anchor; !got.Equal(time.Date(2026, 9, 2, 10, 0, 0, 0, time.UTC)) {
		t.Fatalf("a chat with only its first prompt in flight anchors on that prompt, got %s", got)
	}
	if got := cacheAnchor(writeTranscript(t, `{"type":"summary","summary":"nothing"}`)).anchor; !got.IsZero() {
		t.Fatalf("a transcript with no request must yield the zero anchor, got %s", got)
	}
}

// The cache is refreshed when a request is SENT; the assistant record that
// answers it is stamped after the reply streamed. A 3-minute reply anchored on
// its assistant record showed 3 minutes more cache than there was.
func TestCacheAnchorIsTheRequestNotTheReply(t *testing.T) {
	path := writeTranscript(
		t,
		`{"type":"user","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"user","content":"go"}}`,
		`{"type":"assistant","timestamp":"2026-09-02T10:03:00.000Z","message":{"role":"assistant","content":[]}}`,
	)
	if got := cacheAnchor(path).anchor; !got.Equal(time.Date(2026, 9, 2, 10, 0, 0, 0, time.UTC)) {
		t.Fatalf("cacheAnchor = %s, want the request at 10:00, not the reply at 10:03", got)
	}
	replies := writeTranscript(t,
		`{"type":"assistant","timestamp":"2026-09-02T11:00:00.000Z","message":{"role":"assistant","content":[]}}`,
	)
	if got := cacheAnchor(replies).anchor; !got.Equal(time.Date(2026, 9, 2, 11, 0, 0, 0, time.UTC)) {
		t.Fatalf("a transcript with no request record anchors on its newest reply, got %s", got)
	}
}

// The window's length is what the newest cache write used, read from its
// usage — a chat assumed 1h ran 5m for six hours before this.
func TestCacheWindowLengthComesFromTheNewestWrite(t *testing.T) {
	usage := func(fiveMinutes, oneHour int) string {
		created := fmt.Sprintf(`{"ephemeral_5m_input_tokens":%d,"ephemeral_1h_input_tokens":%d}`, fiveMinutes, oneHour)
		return `{"type":"assistant","timestamp":"2026-09-02T10:00:01.000Z","message":{"role":"assistant","content":[],` +
			`"usage":{"cache_creation":` + created + `}}}`
	}
	request := `{"type":"user","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"user","content":"go"}}`
	for _, tc := range []struct {
		name  string
		lines []string
		want  time.Duration
	}{
		{"a 1h write", []string{request, usage(0, 4193)}, time.Hour},
		{"a 5m write after a 1h one", []string{request, usage(0, 4193), usage(12709, 0)}, 5 * time.Minute},
		{"a pure read keeps the last write's length", []string{request, usage(12709, 0), usage(0, 0)}, 5 * time.Minute},
		{"no breakdown recorded", []string{request}, 0},
	} {
		if got := cacheAnchor(writeTranscript(t, tc.lines...)).ttl; got != tc.want {
			t.Fatalf("%s: ttl = %s, want %s", tc.name, got, tc.want)
		}
	}
}

// The segment labels the window by the measured length even when the
// environment claims the other one, and carries the last call's write.
func TestCacheWindowSegmentUsesMeasuredLengthAndWrite(t *testing.T) {
	now := time.Date(2026, 9, 2, 10, 2, 0, 0, time.UTC)
	path := writeTranscript(
		t,
		`{"type":"user","timestamp":"2026-09-02T10:00:00.000Z","message":{"role":"user","content":"go"}}`,
		`{"type":"assistant","timestamp":"2026-09-02T10:00:30.000Z","message":{"role":"assistant","content":[],`+
			`"usage":{"cache_creation":{"ephemeral_5m_input_tokens":4200,"ephemeral_1h_input_tokens":0}}}}`,
	)
	root := t.TempDir()
	runtime := Runtime{Home: root, CacheDir: filepath.Join(root, "cache"), Env: map[string]string{}}
	got := stripANSICodes(cacheWindowSegment(runtime, now, path, 4200))
	if !strings.Contains(got, "💾5m✓3m:0s +4.2K") {
		t.Fatalf("segment = %q, want the measured 5m window and +4.2K", got)
	}
	if big := cacheWindowSegment(runtime, now, path, 207_108); !strings.Contains(big, cBad+"+207.1K") {
		t.Fatalf("a full re-write must read red: %q", big)
	}
}
