// Tests for scripts/check-opencode-writer.mjs — the stale deleted-writer scan.
// Run: node --test scripts/check-opencode-writer.test.mjs
//
// Each case copies the checker into a throwaway git repository (its ROOT is the
// directory above its own file) beside the five native-remediation surfaces,
// then runs it and reads the exit code and the named lines.

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CHECKER = join(dirname(fileURLToPath(import.meta.url)), "check-opencode-writer.mjs");
// Assembled, never spelled whole: this file is scanned like any other.
const STALE = ["build-opencode", "mjs"].join(".");
const SURFACES = {
  ".github/workflows/verify.yml": "run: go run ./cmd/pfm opencode build ..\n",
  ".github/workflows/plugin-scan.yml": "run: go run ./cmd/pfm opencode build ..\n",
  "scripts/check-agent-roster.mjs": "// go run ./cmd/pfm opencode build ..\n",
  "INSTALL.md": "Run `pfm opencode build .`\n",
  ".gitignore": "# regenerate with pfm opencode build\n",
};

// The fence contract variables and git's own redirects are cleared so a run
// inside dev.sh iso reads the throwaway repository, never the real checkout.
const ENV = { ...process.env };
for (const k of ["PFM_DEV_REPO_GIT_DIR", "PFM_DEV_REPO_WORK_TREE", "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"])
  delete ENV[k];

function tree(files, { git = true } = {}) {
  const root = mkdtempSync(join(tmpdir(), "opencode-writer-"));
  for (const [path, body] of Object.entries({ ...SURFACES, ...files })) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), body);
  }
  copyFileSync(CHECKER, join(root, "scripts", "check-opencode-writer.mjs"));
  if (git) execFileSync("git", ["init", "-q"], { cwd: root, env: ENV });
  return root;
}

function check(root, env = ENV) {
  const r = spawnSync(process.execPath, [join(root, "scripts", "check-opencode-writer.mjs")], {
    cwd: root,
    env,
    encoding: "utf8",
  });
  return { status: r.status, out: r.stdout + r.stderr };
}

test("a clean tree exits 0 and names how many files it scanned", (t) => {
  const root = tree({ "docs/a.md": "nothing stale\n" });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const r = check(root);
  assert.equal(r.status, 0, r.out);
  assert.match(r.out, /opencode-writer: clean — \d+ scanned files/);
});

test("a stale reference in any untracked, unignored file fails by path and line", (t) => {
  const root = tree({ "docs/deep/notes.md": `first\nrun ${STALE} here\n` });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const r = check(root);
  assert.equal(r.status, 1, r.out);
  assert.match(r.out, /opencode-writer: FAIL docs\/deep\/notes\.md:2 — stale deleted writer reference/);
});

test("the exclusions stay silent; any other compiler.go line is still reported", (t) => {
  const root = tree({
    "CHANGELOG.md": `- dropped ${STALE}\n`,
    "releases/v1.0.0.md": `- dropped ${STALE}\n`,
    ".professor/retro.md": `- ${STALE}\n`,
    "pfm/internal/opencodegen/compiler.go": `const oldMarker = "# Generated by ${STALE}"\n// still calls ${STALE}\n`,
  });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const r = check(root);
  assert.equal(r.status, 1, r.out);
  const named = r.out.split("\n").filter((l) => l.includes("stale deleted writer reference"));
  assert.deepEqual(named.map((l) => l.split(" — ")[0]), ["opencode-writer: FAIL pfm/internal/opencodegen/compiler.go:2"]);
});

test("a listed file the scan cannot read is a named failure, never a clean pass", (t) => {
  const root = tree({});
  t.after(() => rmSync(root, { recursive: true, force: true }));
  symlinkSync("loop.md", join(root, "loop.md")); // ELOOP on read — git lists the link itself
  const r = check(root);
  assert.equal(r.status, 1, r.out);
  assert.match(r.out, /opencode-writer: FAIL loop\.md — could not be read \(ELOOP\)/);
});

test("a tree git cannot list fails with scan did not run", (t) => {
  const root = tree({}, { git: false });
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const r = check(root, { ...ENV, GIT_CEILING_DIRECTORIES: dirname(root) });
  assert.equal(r.status, 1, r.out);
  assert.match(r.out, /opencode-writer: FAIL git ls-files — could not list the tree .*scan did not run/s);
});

test("inside the fence the checker lists through PFM_DEV_REPO_GIT_DIR, as the other gates do", (t) => {
  const root = tree({ "docs/a.md": `names ${STALE}\n` }, { git: false });
  const gitDir = mkdtempSync(join(tmpdir(), "opencode-writer-gitdir-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  t.after(() => rmSync(gitDir, { recursive: true, force: true }));
  execFileSync("git", ["init", "-q", `--separate-git-dir=${gitDir}`, root], { env: ENV });
  // The mounted worktree's .git names a host path the container cannot reach.
  writeFileSync(join(root, ".git"), "gitdir: /nonexistent/host/.git/worktrees/develop\n");
  const r = check(root, {
    ...ENV,
    GIT_CEILING_DIRECTORIES: dirname(root),
    PFM_DEV_REPO_GIT_DIR: gitDir,
    PFM_DEV_REPO_WORK_TREE: root,
  });
  assert.equal(r.status, 1, r.out);
  assert.match(r.out, /opencode-writer: FAIL docs\/a\.md:1 — stale deleted writer reference/);
  assert.doesNotMatch(r.out, /could not list the tree/);
});
